// Generated at: 2020-09-11T09:00:20.955Z

export const timezones = [
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmara",
  "Africa/Asmera",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Timbuktu",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca",
  "America/Argentina/ComodRivadavia",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Atikokan",
  "America/Atka",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Buenos_Aires",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Catamarca",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Coral_Harbour",
  "America/Cordoba",
  "America/Costa_Rica",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Ensenada",
  "America/Fort_Nelson",
  "America/Fort_Wayne",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Indianapolis",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Jujuy",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/Knox_IN",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Louisville",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Mendoza",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montreal",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Nuuk",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Porto_Acre",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Punta_Arenas",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Rosario",
  "America/Santa_Isabel",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Shiprock",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Virgin",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/South_Pole",
  "Antarctica/Syowa",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Ashkhabad",
  "Asia/Atyrau",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Calcutta",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Chongqing",
  "Asia/Chungking",
  "Asia/Colombo",
  "Asia/Dacca",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Harbin",
  "Asia/Hebron",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Istanbul",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kashgar",
  "Asia/Kathmandu",
  "Asia/Katmandu",
  "Asia/Khandyga",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macao",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qostanay",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Saigon",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Tel_Aviv",
  "Asia/Thimbu",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ujung_Pandang",
  "Asia/Ulaanbaatar",
  "Asia/Ulan_Bator",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yangon",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faeroe",
  "Atlantic/Faroe",
  "Atlantic/Jan_Mayen",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/ACT",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Canberra",
  "Australia/Currie",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/LHI",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/NSW",
  "Australia/North",
  "Australia/Perth",
  "Australia/Queensland",
  "Australia/South",
  "Australia/Sydney",
  "Australia/Tasmania",
  "Australia/Victoria",
  "Australia/West",
  "Australia/Yancowinna",
  "Brazil/Acre",
  "Brazil/DeNoronha",
  "Brazil/East",
  "Brazil/West",
  "CET",
  "CST6CDT",
  "Canada/Atlantic",
  "Canada/Central",
  "Canada/Eastern",
  "Canada/Mountain",
  "Canada/Newfoundland",
  "Canada/Pacific",
  "Canada/Saskatchewan",
  "Canada/Yukon",
  "Chile/Continental",
  "Chile/EasterIsland",
  "Cuba",
  "EET",
  "EST",
  "EST5EDT",
  "Egypt",
  "Eire",
  "Etc/GMT",
  "Etc/GMT+0",
  "Etc/GMT+1",
  "Etc/GMT+10",
  "Etc/GMT+11",
  "Etc/GMT+12",
  "Etc/GMT+2",
  "Etc/GMT+3",
  "Etc/GMT+4",
  "Etc/GMT+5",
  "Etc/GMT+6",
  "Etc/GMT+7",
  "Etc/GMT+8",
  "Etc/GMT+9",
  "Etc/GMT-0",
  "Etc/GMT-1",
  "Etc/GMT-10",
  "Etc/GMT-11",
  "Etc/GMT-12",
  "Etc/GMT-13",
  "Etc/GMT-14",
  "Etc/GMT-2",
  "Etc/GMT-3",
  "Etc/GMT-4",
  "Etc/GMT-5",
  "Etc/GMT-6",
  "Etc/GMT-7",
  "Etc/GMT-8",
  "Etc/GMT-9",
  "Etc/GMT0",
  "Etc/Greenwich",
  "Etc/UCT",
  "Etc/UTC",
  "Etc/Universal",
  "Etc/Zulu",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belfast",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Nicosia",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Tiraspol",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "GB",
  "GB-Eire",
  "GMT",
  "GMT+0",
  "GMT-0",
  "GMT0",
  "Greenwich",
  "HST",
  "Hongkong",
  "Iceland",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Iran",
  "Israel",
  "Jamaica",
  "Japan",
  "Kwajalein",
  "Libya",
  "MET",
  "MST",
  "MST7MDT",
  "Mexico/BajaNorte",
  "Mexico/BajaSur",
  "Mexico/General",
  "NZ",
  "NZ-CHAT",
  "Navajo",
  "PRC",
  "PST8PDT",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Ponape",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Samoa",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Truk",
  "Pacific/Wake",
  "Pacific/Wallis",
  "Pacific/Yap",
  "Poland",
  "Portugal",
  "ROC",
  "ROK",
  "Singapore",
  "Turkey",
  "UCT",
  "US/Alaska",
  "US/Aleutian",
  "US/Arizona",
  "US/Central",
  "US/East-Indiana",
  "US/Eastern",
  "US/Hawaii",
  "US/Indiana-Starke",
  "US/Michigan",
  "US/Mountain",
  "US/Pacific",
  "US/Pacific-New",
  "US/Samoa",
  "UTC",
  "Universal",
  "W-SU",
  "WET",
  "Zulu"
];

export const timezoneOptions = [
  { value: "Africa/Abidjan", label: "Africa/Abidjan" },
  { value: "Africa/Accra", label: "Africa/Accra" },
  { value: "Africa/Addis_Ababa", label: "Africa/Addis_Ababa" },
  { value: "Africa/Algiers", label: "Africa/Algiers" },
  { value: "Africa/Asmara", label: "Africa/Asmara" },
  { value: "Africa/Asmera", label: "Africa/Asmera" },
  { value: "Africa/Bamako", label: "Africa/Bamako" },
  { value: "Africa/Bangui", label: "Africa/Bangui" },
  { value: "Africa/Banjul", label: "Africa/Banjul" },
  { value: "Africa/Bissau", label: "Africa/Bissau" },
  { value: "Africa/Blantyre", label: "Africa/Blantyre" },
  { value: "Africa/Brazzaville", label: "Africa/Brazzaville" },
  { value: "Africa/Bujumbura", label: "Africa/Bujumbura" },
  { value: "Africa/Cairo", label: "Africa/Cairo" },
  { value: "Africa/Casablanca", label: "Africa/Casablanca" },
  { value: "Africa/Ceuta", label: "Africa/Ceuta" },
  { value: "Africa/Conakry", label: "Africa/Conakry" },
  { value: "Africa/Dakar", label: "Africa/Dakar" },
  { value: "Africa/Dar_es_Salaam", label: "Africa/Dar_es_Salaam" },
  { value: "Africa/Djibouti", label: "Africa/Djibouti" },
  { value: "Africa/Douala", label: "Africa/Douala" },
  { value: "Africa/El_Aaiun", label: "Africa/El_Aaiun" },
  { value: "Africa/Freetown", label: "Africa/Freetown" },
  { value: "Africa/Gaborone", label: "Africa/Gaborone" },
  { value: "Africa/Harare", label: "Africa/Harare" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg" },
  { value: "Africa/Juba", label: "Africa/Juba" },
  { value: "Africa/Kampala", label: "Africa/Kampala" },
  { value: "Africa/Khartoum", label: "Africa/Khartoum" },
  { value: "Africa/Kigali", label: "Africa/Kigali" },
  { value: "Africa/Kinshasa", label: "Africa/Kinshasa" },
  { value: "Africa/Lagos", label: "Africa/Lagos" },
  { value: "Africa/Libreville", label: "Africa/Libreville" },
  { value: "Africa/Lome", label: "Africa/Lome" },
  { value: "Africa/Luanda", label: "Africa/Luanda" },
  { value: "Africa/Lubumbashi", label: "Africa/Lubumbashi" },
  { value: "Africa/Lusaka", label: "Africa/Lusaka" },
  { value: "Africa/Malabo", label: "Africa/Malabo" },
  { value: "Africa/Maputo", label: "Africa/Maputo" },
  { value: "Africa/Maseru", label: "Africa/Maseru" },
  { value: "Africa/Mbabane", label: "Africa/Mbabane" },
  { value: "Africa/Mogadishu", label: "Africa/Mogadishu" },
  { value: "Africa/Monrovia", label: "Africa/Monrovia" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi" },
  { value: "Africa/Ndjamena", label: "Africa/Ndjamena" },
  { value: "Africa/Niamey", label: "Africa/Niamey" },
  { value: "Africa/Nouakchott", label: "Africa/Nouakchott" },
  { value: "Africa/Ouagadougou", label: "Africa/Ouagadougou" },
  { value: "Africa/Porto-Novo", label: "Africa/Porto-Novo" },
  { value: "Africa/Sao_Tome", label: "Africa/Sao_Tome" },
  { value: "Africa/Timbuktu", label: "Africa/Timbuktu" },
  { value: "Africa/Tripoli", label: "Africa/Tripoli" },
  { value: "Africa/Tunis", label: "Africa/Tunis" },
  { value: "Africa/Windhoek", label: "Africa/Windhoek" },
  { value: "America/Adak", label: "America/Adak" },
  { value: "America/Anchorage", label: "America/Anchorage" },
  { value: "America/Anguilla", label: "America/Anguilla" },
  { value: "America/Antigua", label: "America/Antigua" },
  { value: "America/Araguaina", label: "America/Araguaina" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "America/Argentina/Buenos_Aires"
  },
  {
    value: "America/Argentina/Catamarca",
    label: "America/Argentina/Catamarca"
  },
  {
    value: "America/Argentina/ComodRivadavia",
    label: "America/Argentina/ComodRivadavia"
  },
  { value: "America/Argentina/Cordoba", label: "America/Argentina/Cordoba" },
  { value: "America/Argentina/Jujuy", label: "America/Argentina/Jujuy" },
  { value: "America/Argentina/La_Rioja", label: "America/Argentina/La_Rioja" },
  { value: "America/Argentina/Mendoza", label: "America/Argentina/Mendoza" },
  {
    value: "America/Argentina/Rio_Gallegos",
    label: "America/Argentina/Rio_Gallegos"
  },
  { value: "America/Argentina/Salta", label: "America/Argentina/Salta" },
  { value: "America/Argentina/San_Juan", label: "America/Argentina/San_Juan" },
  { value: "America/Argentina/San_Luis", label: "America/Argentina/San_Luis" },
  { value: "America/Argentina/Tucuman", label: "America/Argentina/Tucuman" },
  { value: "America/Argentina/Ushuaia", label: "America/Argentina/Ushuaia" },
  { value: "America/Aruba", label: "America/Aruba" },
  { value: "America/Asuncion", label: "America/Asuncion" },
  { value: "America/Atikokan", label: "America/Atikokan" },
  { value: "America/Atka", label: "America/Atka" },
  { value: "America/Bahia", label: "America/Bahia" },
  { value: "America/Bahia_Banderas", label: "America/Bahia_Banderas" },
  { value: "America/Barbados", label: "America/Barbados" },
  { value: "America/Belem", label: "America/Belem" },
  { value: "America/Belize", label: "America/Belize" },
  { value: "America/Blanc-Sablon", label: "America/Blanc-Sablon" },
  { value: "America/Boa_Vista", label: "America/Boa_Vista" },
  { value: "America/Bogota", label: "America/Bogota" },
  { value: "America/Boise", label: "America/Boise" },
  { value: "America/Buenos_Aires", label: "America/Buenos_Aires" },
  { value: "America/Cambridge_Bay", label: "America/Cambridge_Bay" },
  { value: "America/Campo_Grande", label: "America/Campo_Grande" },
  { value: "America/Cancun", label: "America/Cancun" },
  { value: "America/Caracas", label: "America/Caracas" },
  { value: "America/Catamarca", label: "America/Catamarca" },
  { value: "America/Cayenne", label: "America/Cayenne" },
  { value: "America/Cayman", label: "America/Cayman" },
  { value: "America/Chicago", label: "America/Chicago" },
  { value: "America/Chihuahua", label: "America/Chihuahua" },
  { value: "America/Coral_Harbour", label: "America/Coral_Harbour" },
  { value: "America/Cordoba", label: "America/Cordoba" },
  { value: "America/Costa_Rica", label: "America/Costa_Rica" },
  { value: "America/Creston", label: "America/Creston" },
  { value: "America/Cuiaba", label: "America/Cuiaba" },
  { value: "America/Curacao", label: "America/Curacao" },
  { value: "America/Danmarkshavn", label: "America/Danmarkshavn" },
  { value: "America/Dawson", label: "America/Dawson" },
  { value: "America/Dawson_Creek", label: "America/Dawson_Creek" },
  { value: "America/Denver", label: "America/Denver" },
  { value: "America/Detroit", label: "America/Detroit" },
  { value: "America/Dominica", label: "America/Dominica" },
  { value: "America/Edmonton", label: "America/Edmonton" },
  { value: "America/Eirunepe", label: "America/Eirunepe" },
  { value: "America/El_Salvador", label: "America/El_Salvador" },
  { value: "America/Ensenada", label: "America/Ensenada" },
  { value: "America/Fort_Nelson", label: "America/Fort_Nelson" },
  { value: "America/Fort_Wayne", label: "America/Fort_Wayne" },
  { value: "America/Fortaleza", label: "America/Fortaleza" },
  { value: "America/Glace_Bay", label: "America/Glace_Bay" },
  { value: "America/Godthab", label: "America/Godthab" },
  { value: "America/Goose_Bay", label: "America/Goose_Bay" },
  { value: "America/Grand_Turk", label: "America/Grand_Turk" },
  { value: "America/Grenada", label: "America/Grenada" },
  { value: "America/Guadeloupe", label: "America/Guadeloupe" },
  { value: "America/Guatemala", label: "America/Guatemala" },
  { value: "America/Guayaquil", label: "America/Guayaquil" },
  { value: "America/Guyana", label: "America/Guyana" },
  { value: "America/Halifax", label: "America/Halifax" },
  { value: "America/Havana", label: "America/Havana" },
  { value: "America/Hermosillo", label: "America/Hermosillo" },
  {
    value: "America/Indiana/Indianapolis",
    label: "America/Indiana/Indianapolis"
  },
  { value: "America/Indiana/Knox", label: "America/Indiana/Knox" },
  { value: "America/Indiana/Marengo", label: "America/Indiana/Marengo" },
  { value: "America/Indiana/Petersburg", label: "America/Indiana/Petersburg" },
  { value: "America/Indiana/Tell_City", label: "America/Indiana/Tell_City" },
  { value: "America/Indiana/Vevay", label: "America/Indiana/Vevay" },
  { value: "America/Indiana/Vincennes", label: "America/Indiana/Vincennes" },
  { value: "America/Indiana/Winamac", label: "America/Indiana/Winamac" },
  { value: "America/Indianapolis", label: "America/Indianapolis" },
  { value: "America/Inuvik", label: "America/Inuvik" },
  { value: "America/Iqaluit", label: "America/Iqaluit" },
  { value: "America/Jamaica", label: "America/Jamaica" },
  { value: "America/Jujuy", label: "America/Jujuy" },
  { value: "America/Juneau", label: "America/Juneau" },
  {
    value: "America/Kentucky/Louisville",
    label: "America/Kentucky/Louisville"
  },
  {
    value: "America/Kentucky/Monticello",
    label: "America/Kentucky/Monticello"
  },
  { value: "America/Knox_IN", label: "America/Knox_IN" },
  { value: "America/Kralendijk", label: "America/Kralendijk" },
  { value: "America/La_Paz", label: "America/La_Paz" },
  { value: "America/Lima", label: "America/Lima" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles" },
  { value: "America/Louisville", label: "America/Louisville" },
  { value: "America/Lower_Princes", label: "America/Lower_Princes" },
  { value: "America/Maceio", label: "America/Maceio" },
  { value: "America/Managua", label: "America/Managua" },
  { value: "America/Manaus", label: "America/Manaus" },
  { value: "America/Marigot", label: "America/Marigot" },
  { value: "America/Martinique", label: "America/Martinique" },
  { value: "America/Matamoros", label: "America/Matamoros" },
  { value: "America/Mazatlan", label: "America/Mazatlan" },
  { value: "America/Mendoza", label: "America/Mendoza" },
  { value: "America/Menominee", label: "America/Menominee" },
  { value: "America/Merida", label: "America/Merida" },
  { value: "America/Metlakatla", label: "America/Metlakatla" },
  { value: "America/Mexico_City", label: "America/Mexico_City" },
  { value: "America/Miquelon", label: "America/Miquelon" },
  { value: "America/Moncton", label: "America/Moncton" },
  { value: "America/Monterrey", label: "America/Monterrey" },
  { value: "America/Montevideo", label: "America/Montevideo" },
  { value: "America/Montreal", label: "America/Montreal" },
  { value: "America/Montserrat", label: "America/Montserrat" },
  { value: "America/Nassau", label: "America/Nassau" },
  { value: "America/New_York", label: "America/New_York" },
  { value: "America/Nipigon", label: "America/Nipigon" },
  { value: "America/Nome", label: "America/Nome" },
  { value: "America/Noronha", label: "America/Noronha" },
  {
    value: "America/North_Dakota/Beulah",
    label: "America/North_Dakota/Beulah"
  },
  {
    value: "America/North_Dakota/Center",
    label: "America/North_Dakota/Center"
  },
  {
    value: "America/North_Dakota/New_Salem",
    label: "America/North_Dakota/New_Salem"
  },
  { value: "America/Nuuk", label: "America/Nuuk" },
  { value: "America/Ojinaga", label: "America/Ojinaga" },
  { value: "America/Panama", label: "America/Panama" },
  { value: "America/Pangnirtung", label: "America/Pangnirtung" },
  { value: "America/Paramaribo", label: "America/Paramaribo" },
  { value: "America/Phoenix", label: "America/Phoenix" },
  { value: "America/Port-au-Prince", label: "America/Port-au-Prince" },
  { value: "America/Port_of_Spain", label: "America/Port_of_Spain" },
  { value: "America/Porto_Acre", label: "America/Porto_Acre" },
  { value: "America/Porto_Velho", label: "America/Porto_Velho" },
  { value: "America/Puerto_Rico", label: "America/Puerto_Rico" },
  { value: "America/Punta_Arenas", label: "America/Punta_Arenas" },
  { value: "America/Rainy_River", label: "America/Rainy_River" },
  { value: "America/Rankin_Inlet", label: "America/Rankin_Inlet" },
  { value: "America/Recife", label: "America/Recife" },
  { value: "America/Regina", label: "America/Regina" },
  { value: "America/Resolute", label: "America/Resolute" },
  { value: "America/Rio_Branco", label: "America/Rio_Branco" },
  { value: "America/Rosario", label: "America/Rosario" },
  { value: "America/Santa_Isabel", label: "America/Santa_Isabel" },
  { value: "America/Santarem", label: "America/Santarem" },
  { value: "America/Santiago", label: "America/Santiago" },
  { value: "America/Santo_Domingo", label: "America/Santo_Domingo" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo" },
  { value: "America/Scoresbysund", label: "America/Scoresbysund" },
  { value: "America/Shiprock", label: "America/Shiprock" },
  { value: "America/Sitka", label: "America/Sitka" },
  { value: "America/St_Barthelemy", label: "America/St_Barthelemy" },
  { value: "America/St_Johns", label: "America/St_Johns" },
  { value: "America/St_Kitts", label: "America/St_Kitts" },
  { value: "America/St_Lucia", label: "America/St_Lucia" },
  { value: "America/St_Thomas", label: "America/St_Thomas" },
  { value: "America/St_Vincent", label: "America/St_Vincent" },
  { value: "America/Swift_Current", label: "America/Swift_Current" },
  { value: "America/Tegucigalpa", label: "America/Tegucigalpa" },
  { value: "America/Thule", label: "America/Thule" },
  { value: "America/Thunder_Bay", label: "America/Thunder_Bay" },
  { value: "America/Tijuana", label: "America/Tijuana" },
  { value: "America/Toronto", label: "America/Toronto" },
  { value: "America/Tortola", label: "America/Tortola" },
  { value: "America/Vancouver", label: "America/Vancouver" },
  { value: "America/Virgin", label: "America/Virgin" },
  { value: "America/Whitehorse", label: "America/Whitehorse" },
  { value: "America/Winnipeg", label: "America/Winnipeg" },
  { value: "America/Yakutat", label: "America/Yakutat" },
  { value: "America/Yellowknife", label: "America/Yellowknife" },
  { value: "Antarctica/Casey", label: "Antarctica/Casey" },
  { value: "Antarctica/Davis", label: "Antarctica/Davis" },
  { value: "Antarctica/DumontDUrville", label: "Antarctica/DumontDUrville" },
  { value: "Antarctica/Macquarie", label: "Antarctica/Macquarie" },
  { value: "Antarctica/Mawson", label: "Antarctica/Mawson" },
  { value: "Antarctica/McMurdo", label: "Antarctica/McMurdo" },
  { value: "Antarctica/Palmer", label: "Antarctica/Palmer" },
  { value: "Antarctica/Rothera", label: "Antarctica/Rothera" },
  { value: "Antarctica/South_Pole", label: "Antarctica/South_Pole" },
  { value: "Antarctica/Syowa", label: "Antarctica/Syowa" },
  { value: "Antarctica/Troll", label: "Antarctica/Troll" },
  { value: "Antarctica/Vostok", label: "Antarctica/Vostok" },
  { value: "Arctic/Longyearbyen", label: "Arctic/Longyearbyen" },
  { value: "Asia/Aden", label: "Asia/Aden" },
  { value: "Asia/Almaty", label: "Asia/Almaty" },
  { value: "Asia/Amman", label: "Asia/Amman" },
  { value: "Asia/Anadyr", label: "Asia/Anadyr" },
  { value: "Asia/Aqtau", label: "Asia/Aqtau" },
  { value: "Asia/Aqtobe", label: "Asia/Aqtobe" },
  { value: "Asia/Ashgabat", label: "Asia/Ashgabat" },
  { value: "Asia/Ashkhabad", label: "Asia/Ashkhabad" },
  { value: "Asia/Atyrau", label: "Asia/Atyrau" },
  { value: "Asia/Baghdad", label: "Asia/Baghdad" },
  { value: "Asia/Bahrain", label: "Asia/Bahrain" },
  { value: "Asia/Baku", label: "Asia/Baku" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok" },
  { value: "Asia/Barnaul", label: "Asia/Barnaul" },
  { value: "Asia/Beirut", label: "Asia/Beirut" },
  { value: "Asia/Bishkek", label: "Asia/Bishkek" },
  { value: "Asia/Brunei", label: "Asia/Brunei" },
  { value: "Asia/Calcutta", label: "Asia/Calcutta" },
  { value: "Asia/Chita", label: "Asia/Chita" },
  { value: "Asia/Choibalsan", label: "Asia/Choibalsan" },
  { value: "Asia/Chongqing", label: "Asia/Chongqing" },
  { value: "Asia/Chungking", label: "Asia/Chungking" },
  { value: "Asia/Colombo", label: "Asia/Colombo" },
  { value: "Asia/Dacca", label: "Asia/Dacca" },
  { value: "Asia/Damascus", label: "Asia/Damascus" },
  { value: "Asia/Dhaka", label: "Asia/Dhaka" },
  { value: "Asia/Dili", label: "Asia/Dili" },
  { value: "Asia/Dubai", label: "Asia/Dubai" },
  { value: "Asia/Dushanbe", label: "Asia/Dushanbe" },
  { value: "Asia/Famagusta", label: "Asia/Famagusta" },
  { value: "Asia/Gaza", label: "Asia/Gaza" },
  { value: "Asia/Harbin", label: "Asia/Harbin" },
  { value: "Asia/Hebron", label: "Asia/Hebron" },
  { value: "Asia/Ho_Chi_Minh", label: "Asia/Ho_Chi_Minh" },
  { value: "Asia/Hong_Kong", label: "Asia/Hong_Kong" },
  { value: "Asia/Hovd", label: "Asia/Hovd" },
  { value: "Asia/Irkutsk", label: "Asia/Irkutsk" },
  { value: "Asia/Istanbul", label: "Asia/Istanbul" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta" },
  { value: "Asia/Jayapura", label: "Asia/Jayapura" },
  { value: "Asia/Jerusalem", label: "Asia/Jerusalem" },
  { value: "Asia/Kabul", label: "Asia/Kabul" },
  { value: "Asia/Kamchatka", label: "Asia/Kamchatka" },
  { value: "Asia/Karachi", label: "Asia/Karachi" },
  { value: "Asia/Kashgar", label: "Asia/Kashgar" },
  { value: "Asia/Kathmandu", label: "Asia/Kathmandu" },
  { value: "Asia/Katmandu", label: "Asia/Katmandu" },
  { value: "Asia/Khandyga", label: "Asia/Khandyga" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata" },
  { value: "Asia/Krasnoyarsk", label: "Asia/Krasnoyarsk" },
  { value: "Asia/Kuala_Lumpur", label: "Asia/Kuala_Lumpur" },
  { value: "Asia/Kuching", label: "Asia/Kuching" },
  { value: "Asia/Kuwait", label: "Asia/Kuwait" },
  { value: "Asia/Macao", label: "Asia/Macao" },
  { value: "Asia/Macau", label: "Asia/Macau" },
  { value: "Asia/Magadan", label: "Asia/Magadan" },
  { value: "Asia/Makassar", label: "Asia/Makassar" },
  { value: "Asia/Manila", label: "Asia/Manila" },
  { value: "Asia/Muscat", label: "Asia/Muscat" },
  { value: "Asia/Nicosia", label: "Asia/Nicosia" },
  { value: "Asia/Novokuznetsk", label: "Asia/Novokuznetsk" },
  { value: "Asia/Novosibirsk", label: "Asia/Novosibirsk" },
  { value: "Asia/Omsk", label: "Asia/Omsk" },
  { value: "Asia/Oral", label: "Asia/Oral" },
  { value: "Asia/Phnom_Penh", label: "Asia/Phnom_Penh" },
  { value: "Asia/Pontianak", label: "Asia/Pontianak" },
  { value: "Asia/Pyongyang", label: "Asia/Pyongyang" },
  { value: "Asia/Qatar", label: "Asia/Qatar" },
  { value: "Asia/Qostanay", label: "Asia/Qostanay" },
  { value: "Asia/Qyzylorda", label: "Asia/Qyzylorda" },
  { value: "Asia/Rangoon", label: "Asia/Rangoon" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh" },
  { value: "Asia/Saigon", label: "Asia/Saigon" },
  { value: "Asia/Sakhalin", label: "Asia/Sakhalin" },
  { value: "Asia/Samarkand", label: "Asia/Samarkand" },
  { value: "Asia/Seoul", label: "Asia/Seoul" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai" },
  { value: "Asia/Singapore", label: "Asia/Singapore" },
  { value: "Asia/Srednekolymsk", label: "Asia/Srednekolymsk" },
  { value: "Asia/Taipei", label: "Asia/Taipei" },
  { value: "Asia/Tashkent", label: "Asia/Tashkent" },
  { value: "Asia/Tbilisi", label: "Asia/Tbilisi" },
  { value: "Asia/Tehran", label: "Asia/Tehran" },
  { value: "Asia/Tel_Aviv", label: "Asia/Tel_Aviv" },
  { value: "Asia/Thimbu", label: "Asia/Thimbu" },
  { value: "Asia/Thimphu", label: "Asia/Thimphu" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo" },
  { value: "Asia/Tomsk", label: "Asia/Tomsk" },
  { value: "Asia/Ujung_Pandang", label: "Asia/Ujung_Pandang" },
  { value: "Asia/Ulaanbaatar", label: "Asia/Ulaanbaatar" },
  { value: "Asia/Ulan_Bator", label: "Asia/Ulan_Bator" },
  { value: "Asia/Urumqi", label: "Asia/Urumqi" },
  { value: "Asia/Ust-Nera", label: "Asia/Ust-Nera" },
  { value: "Asia/Vientiane", label: "Asia/Vientiane" },
  { value: "Asia/Vladivostok", label: "Asia/Vladivostok" },
  { value: "Asia/Yakutsk", label: "Asia/Yakutsk" },
  { value: "Asia/Yangon", label: "Asia/Yangon" },
  { value: "Asia/Yekaterinburg", label: "Asia/Yekaterinburg" },
  { value: "Asia/Yerevan", label: "Asia/Yerevan" },
  { value: "Atlantic/Azores", label: "Atlantic/Azores" },
  { value: "Atlantic/Bermuda", label: "Atlantic/Bermuda" },
  { value: "Atlantic/Canary", label: "Atlantic/Canary" },
  { value: "Atlantic/Cape_Verde", label: "Atlantic/Cape_Verde" },
  { value: "Atlantic/Faeroe", label: "Atlantic/Faeroe" },
  { value: "Atlantic/Faroe", label: "Atlantic/Faroe" },
  { value: "Atlantic/Jan_Mayen", label: "Atlantic/Jan_Mayen" },
  { value: "Atlantic/Madeira", label: "Atlantic/Madeira" },
  { value: "Atlantic/Reykjavik", label: "Atlantic/Reykjavik" },
  { value: "Atlantic/South_Georgia", label: "Atlantic/South_Georgia" },
  { value: "Atlantic/St_Helena", label: "Atlantic/St_Helena" },
  { value: "Atlantic/Stanley", label: "Atlantic/Stanley" },
  { value: "Australia/ACT", label: "Australia/ACT" },
  { value: "Australia/Adelaide", label: "Australia/Adelaide" },
  { value: "Australia/Brisbane", label: "Australia/Brisbane" },
  { value: "Australia/Broken_Hill", label: "Australia/Broken_Hill" },
  { value: "Australia/Canberra", label: "Australia/Canberra" },
  { value: "Australia/Currie", label: "Australia/Currie" },
  { value: "Australia/Darwin", label: "Australia/Darwin" },
  { value: "Australia/Eucla", label: "Australia/Eucla" },
  { value: "Australia/Hobart", label: "Australia/Hobart" },
  { value: "Australia/LHI", label: "Australia/LHI" },
  { value: "Australia/Lindeman", label: "Australia/Lindeman" },
  { value: "Australia/Lord_Howe", label: "Australia/Lord_Howe" },
  { value: "Australia/Melbourne", label: "Australia/Melbourne" },
  { value: "Australia/NSW", label: "Australia/NSW" },
  { value: "Australia/North", label: "Australia/North" },
  { value: "Australia/Perth", label: "Australia/Perth" },
  { value: "Australia/Queensland", label: "Australia/Queensland" },
  { value: "Australia/South", label: "Australia/South" },
  { value: "Australia/Sydney", label: "Australia/Sydney" },
  { value: "Australia/Tasmania", label: "Australia/Tasmania" },
  { value: "Australia/Victoria", label: "Australia/Victoria" },
  { value: "Australia/West", label: "Australia/West" },
  { value: "Australia/Yancowinna", label: "Australia/Yancowinna" },
  { value: "Brazil/Acre", label: "Brazil/Acre" },
  { value: "Brazil/DeNoronha", label: "Brazil/DeNoronha" },
  { value: "Brazil/East", label: "Brazil/East" },
  { value: "Brazil/West", label: "Brazil/West" },
  { value: "CET", label: "CET" },
  { value: "CST6CDT", label: "CST6CDT" },
  { value: "Canada/Atlantic", label: "Canada/Atlantic" },
  { value: "Canada/Central", label: "Canada/Central" },
  { value: "Canada/Eastern", label: "Canada/Eastern" },
  { value: "Canada/Mountain", label: "Canada/Mountain" },
  { value: "Canada/Newfoundland", label: "Canada/Newfoundland" },
  { value: "Canada/Pacific", label: "Canada/Pacific" },
  { value: "Canada/Saskatchewan", label: "Canada/Saskatchewan" },
  { value: "Canada/Yukon", label: "Canada/Yukon" },
  { value: "Chile/Continental", label: "Chile/Continental" },
  { value: "Chile/EasterIsland", label: "Chile/EasterIsland" },
  { value: "Cuba", label: "Cuba" },
  { value: "EET", label: "EET" },
  { value: "EST", label: "EST" },
  { value: "EST5EDT", label: "EST5EDT" },
  { value: "Egypt", label: "Egypt" },
  { value: "Eire", label: "Eire" },
  { value: "Etc/GMT", label: "Etc/GMT" },
  { value: "Etc/GMT+0", label: "Etc/GMT+0" },
  { value: "Etc/GMT+1", label: "Etc/GMT+1" },
  { value: "Etc/GMT+10", label: "Etc/GMT+10" },
  { value: "Etc/GMT+11", label: "Etc/GMT+11" },
  { value: "Etc/GMT+12", label: "Etc/GMT+12" },
  { value: "Etc/GMT+2", label: "Etc/GMT+2" },
  { value: "Etc/GMT+3", label: "Etc/GMT+3" },
  { value: "Etc/GMT+4", label: "Etc/GMT+4" },
  { value: "Etc/GMT+5", label: "Etc/GMT+5" },
  { value: "Etc/GMT+6", label: "Etc/GMT+6" },
  { value: "Etc/GMT+7", label: "Etc/GMT+7" },
  { value: "Etc/GMT+8", label: "Etc/GMT+8" },
  { value: "Etc/GMT+9", label: "Etc/GMT+9" },
  { value: "Etc/GMT-0", label: "Etc/GMT-0" },
  { value: "Etc/GMT-1", label: "Etc/GMT-1" },
  { value: "Etc/GMT-10", label: "Etc/GMT-10" },
  { value: "Etc/GMT-11", label: "Etc/GMT-11" },
  { value: "Etc/GMT-12", label: "Etc/GMT-12" },
  { value: "Etc/GMT-13", label: "Etc/GMT-13" },
  { value: "Etc/GMT-14", label: "Etc/GMT-14" },
  { value: "Etc/GMT-2", label: "Etc/GMT-2" },
  { value: "Etc/GMT-3", label: "Etc/GMT-3" },
  { value: "Etc/GMT-4", label: "Etc/GMT-4" },
  { value: "Etc/GMT-5", label: "Etc/GMT-5" },
  { value: "Etc/GMT-6", label: "Etc/GMT-6" },
  { value: "Etc/GMT-7", label: "Etc/GMT-7" },
  { value: "Etc/GMT-8", label: "Etc/GMT-8" },
  { value: "Etc/GMT-9", label: "Etc/GMT-9" },
  { value: "Etc/GMT0", label: "Etc/GMT0" },
  { value: "Etc/Greenwich", label: "Etc/Greenwich" },
  { value: "Etc/UCT", label: "Etc/UCT" },
  { value: "Etc/UTC", label: "Etc/UTC" },
  { value: "Etc/Universal", label: "Etc/Universal" },
  { value: "Etc/Zulu", label: "Etc/Zulu" },
  { value: "Europe/Amsterdam", label: "Europe/Amsterdam" },
  { value: "Europe/Andorra", label: "Europe/Andorra" },
  { value: "Europe/Astrakhan", label: "Europe/Astrakhan" },
  { value: "Europe/Athens", label: "Europe/Athens" },
  { value: "Europe/Belfast", label: "Europe/Belfast" },
  { value: "Europe/Belgrade", label: "Europe/Belgrade" },
  { value: "Europe/Berlin", label: "Europe/Berlin" },
  { value: "Europe/Bratislava", label: "Europe/Bratislava" },
  { value: "Europe/Brussels", label: "Europe/Brussels" },
  { value: "Europe/Bucharest", label: "Europe/Bucharest" },
  { value: "Europe/Budapest", label: "Europe/Budapest" },
  { value: "Europe/Busingen", label: "Europe/Busingen" },
  { value: "Europe/Chisinau", label: "Europe/Chisinau" },
  { value: "Europe/Copenhagen", label: "Europe/Copenhagen" },
  { value: "Europe/Dublin", label: "Europe/Dublin" },
  { value: "Europe/Gibraltar", label: "Europe/Gibraltar" },
  { value: "Europe/Guernsey", label: "Europe/Guernsey" },
  { value: "Europe/Helsinki", label: "Europe/Helsinki" },
  { value: "Europe/Isle_of_Man", label: "Europe/Isle_of_Man" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul" },
  { value: "Europe/Jersey", label: "Europe/Jersey" },
  { value: "Europe/Kaliningrad", label: "Europe/Kaliningrad" },
  { value: "Europe/Kiev", label: "Europe/Kiev" },
  { value: "Europe/Kirov", label: "Europe/Kirov" },
  { value: "Europe/Lisbon", label: "Europe/Lisbon" },
  { value: "Europe/Ljubljana", label: "Europe/Ljubljana" },
  { value: "Europe/London", label: "Europe/London" },
  { value: "Europe/Luxembourg", label: "Europe/Luxembourg" },
  { value: "Europe/Madrid", label: "Europe/Madrid" },
  { value: "Europe/Malta", label: "Europe/Malta" },
  { value: "Europe/Mariehamn", label: "Europe/Mariehamn" },
  { value: "Europe/Minsk", label: "Europe/Minsk" },
  { value: "Europe/Monaco", label: "Europe/Monaco" },
  { value: "Europe/Moscow", label: "Europe/Moscow" },
  { value: "Europe/Nicosia", label: "Europe/Nicosia" },
  { value: "Europe/Oslo", label: "Europe/Oslo" },
  { value: "Europe/Paris", label: "Europe/Paris" },
  { value: "Europe/Podgorica", label: "Europe/Podgorica" },
  { value: "Europe/Prague", label: "Europe/Prague" },
  { value: "Europe/Riga", label: "Europe/Riga" },
  { value: "Europe/Rome", label: "Europe/Rome" },
  { value: "Europe/Samara", label: "Europe/Samara" },
  { value: "Europe/San_Marino", label: "Europe/San_Marino" },
  { value: "Europe/Sarajevo", label: "Europe/Sarajevo" },
  { value: "Europe/Saratov", label: "Europe/Saratov" },
  { value: "Europe/Simferopol", label: "Europe/Simferopol" },
  { value: "Europe/Skopje", label: "Europe/Skopje" },
  { value: "Europe/Sofia", label: "Europe/Sofia" },
  { value: "Europe/Stockholm", label: "Europe/Stockholm" },
  { value: "Europe/Tallinn", label: "Europe/Tallinn" },
  { value: "Europe/Tirane", label: "Europe/Tirane" },
  { value: "Europe/Tiraspol", label: "Europe/Tiraspol" },
  { value: "Europe/Ulyanovsk", label: "Europe/Ulyanovsk" },
  { value: "Europe/Uzhgorod", label: "Europe/Uzhgorod" },
  { value: "Europe/Vaduz", label: "Europe/Vaduz" },
  { value: "Europe/Vatican", label: "Europe/Vatican" },
  { value: "Europe/Vienna", label: "Europe/Vienna" },
  { value: "Europe/Vilnius", label: "Europe/Vilnius" },
  { value: "Europe/Volgograd", label: "Europe/Volgograd" },
  { value: "Europe/Warsaw", label: "Europe/Warsaw" },
  { value: "Europe/Zagreb", label: "Europe/Zagreb" },
  { value: "Europe/Zaporozhye", label: "Europe/Zaporozhye" },
  { value: "Europe/Zurich", label: "Europe/Zurich" },
  { value: "GB", label: "GB" },
  { value: "GB-Eire", label: "GB-Eire" },
  { value: "GMT", label: "GMT" },
  { value: "GMT+0", label: "GMT+0" },
  { value: "GMT-0", label: "GMT-0" },
  { value: "GMT0", label: "GMT0" },
  { value: "Greenwich", label: "Greenwich" },
  { value: "HST", label: "HST" },
  { value: "Hongkong", label: "Hongkong" },
  { value: "Iceland", label: "Iceland" },
  { value: "Indian/Antananarivo", label: "Indian/Antananarivo" },
  { value: "Indian/Chagos", label: "Indian/Chagos" },
  { value: "Indian/Christmas", label: "Indian/Christmas" },
  { value: "Indian/Cocos", label: "Indian/Cocos" },
  { value: "Indian/Comoro", label: "Indian/Comoro" },
  { value: "Indian/Kerguelen", label: "Indian/Kerguelen" },
  { value: "Indian/Mahe", label: "Indian/Mahe" },
  { value: "Indian/Maldives", label: "Indian/Maldives" },
  { value: "Indian/Mauritius", label: "Indian/Mauritius" },
  { value: "Indian/Mayotte", label: "Indian/Mayotte" },
  { value: "Indian/Reunion", label: "Indian/Reunion" },
  { value: "Iran", label: "Iran" },
  { value: "Israel", label: "Israel" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Japan", label: "Japan" },
  { value: "Kwajalein", label: "Kwajalein" },
  { value: "Libya", label: "Libya" },
  { value: "MET", label: "MET" },
  { value: "MST", label: "MST" },
  { value: "MST7MDT", label: "MST7MDT" },
  { value: "Mexico/BajaNorte", label: "Mexico/BajaNorte" },
  { value: "Mexico/BajaSur", label: "Mexico/BajaSur" },
  { value: "Mexico/General", label: "Mexico/General" },
  { value: "NZ", label: "NZ" },
  { value: "NZ-CHAT", label: "NZ-CHAT" },
  { value: "Navajo", label: "Navajo" },
  { value: "PRC", label: "PRC" },
  { value: "PST8PDT", label: "PST8PDT" },
  { value: "Pacific/Apia", label: "Pacific/Apia" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland" },
  { value: "Pacific/Bougainville", label: "Pacific/Bougainville" },
  { value: "Pacific/Chatham", label: "Pacific/Chatham" },
  { value: "Pacific/Chuuk", label: "Pacific/Chuuk" },
  { value: "Pacific/Easter", label: "Pacific/Easter" },
  { value: "Pacific/Efate", label: "Pacific/Efate" },
  { value: "Pacific/Enderbury", label: "Pacific/Enderbury" },
  { value: "Pacific/Fakaofo", label: "Pacific/Fakaofo" },
  { value: "Pacific/Fiji", label: "Pacific/Fiji" },
  { value: "Pacific/Funafuti", label: "Pacific/Funafuti" },
  { value: "Pacific/Galapagos", label: "Pacific/Galapagos" },
  { value: "Pacific/Gambier", label: "Pacific/Gambier" },
  { value: "Pacific/Guadalcanal", label: "Pacific/Guadalcanal" },
  { value: "Pacific/Guam", label: "Pacific/Guam" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu" },
  { value: "Pacific/Johnston", label: "Pacific/Johnston" },
  { value: "Pacific/Kiritimati", label: "Pacific/Kiritimati" },
  { value: "Pacific/Kosrae", label: "Pacific/Kosrae" },
  { value: "Pacific/Kwajalein", label: "Pacific/Kwajalein" },
  { value: "Pacific/Majuro", label: "Pacific/Majuro" },
  { value: "Pacific/Marquesas", label: "Pacific/Marquesas" },
  { value: "Pacific/Midway", label: "Pacific/Midway" },
  { value: "Pacific/Nauru", label: "Pacific/Nauru" },
  { value: "Pacific/Niue", label: "Pacific/Niue" },
  { value: "Pacific/Norfolk", label: "Pacific/Norfolk" },
  { value: "Pacific/Noumea", label: "Pacific/Noumea" },
  { value: "Pacific/Pago_Pago", label: "Pacific/Pago_Pago" },
  { value: "Pacific/Palau", label: "Pacific/Palau" },
  { value: "Pacific/Pitcairn", label: "Pacific/Pitcairn" },
  { value: "Pacific/Pohnpei", label: "Pacific/Pohnpei" },
  { value: "Pacific/Ponape", label: "Pacific/Ponape" },
  { value: "Pacific/Port_Moresby", label: "Pacific/Port_Moresby" },
  { value: "Pacific/Rarotonga", label: "Pacific/Rarotonga" },
  { value: "Pacific/Saipan", label: "Pacific/Saipan" },
  { value: "Pacific/Samoa", label: "Pacific/Samoa" },
  { value: "Pacific/Tahiti", label: "Pacific/Tahiti" },
  { value: "Pacific/Tarawa", label: "Pacific/Tarawa" },
  { value: "Pacific/Tongatapu", label: "Pacific/Tongatapu" },
  { value: "Pacific/Truk", label: "Pacific/Truk" },
  { value: "Pacific/Wake", label: "Pacific/Wake" },
  { value: "Pacific/Wallis", label: "Pacific/Wallis" },
  { value: "Pacific/Yap", label: "Pacific/Yap" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "ROC", label: "ROC" },
  { value: "ROK", label: "ROK" },
  { value: "Singapore", label: "Singapore" },
  { value: "Turkey", label: "Turkey" },
  { value: "UCT", label: "UCT" },
  { value: "US/Alaska", label: "US/Alaska" },
  { value: "US/Aleutian", label: "US/Aleutian" },
  { value: "US/Arizona", label: "US/Arizona" },
  { value: "US/Central", label: "US/Central" },
  { value: "US/East-Indiana", label: "US/East-Indiana" },
  { value: "US/Eastern", label: "US/Eastern" },
  { value: "US/Hawaii", label: "US/Hawaii" },
  { value: "US/Indiana-Starke", label: "US/Indiana-Starke" },
  { value: "US/Michigan", label: "US/Michigan" },
  { value: "US/Mountain", label: "US/Mountain" },
  { value: "US/Pacific", label: "US/Pacific" },
  { value: "US/Pacific-New", label: "US/Pacific-New" },
  { value: "US/Samoa", label: "US/Samoa" },
  { value: "UTC", label: "UTC" },
  { value: "Universal", label: "Universal" },
  { value: "W-SU", label: "W-SU" },
  { value: "WET", label: "WET" },
  { value: "Zulu", label: "Zulu" }
];

export enum Timezone {
  AfricaAbidjan = "Africa/Abidjan",
  AfricaAccra = "Africa/Accra",
  AfricaAddisAbaba = "Africa/Addis_Ababa",
  AfricaAlgiers = "Africa/Algiers",
  AfricaAsmara = "Africa/Asmara",
  AfricaAsmera = "Africa/Asmera",
  AfricaBamako = "Africa/Bamako",
  AfricaBangui = "Africa/Bangui",
  AfricaBanjul = "Africa/Banjul",
  AfricaBissau = "Africa/Bissau",
  AfricaBlantyre = "Africa/Blantyre",
  AfricaBrazzaville = "Africa/Brazzaville",
  AfricaBujumbura = "Africa/Bujumbura",
  AfricaCairo = "Africa/Cairo",
  AfricaCasablanca = "Africa/Casablanca",
  AfricaCeuta = "Africa/Ceuta",
  AfricaConakry = "Africa/Conakry",
  AfricaDakar = "Africa/Dakar",
  AfricaDaresSalaam = "Africa/Dar_es_Salaam",
  AfricaDjibouti = "Africa/Djibouti",
  AfricaDouala = "Africa/Douala",
  AfricaElAaiun = "Africa/El_Aaiun",
  AfricaFreetown = "Africa/Freetown",
  AfricaGaborone = "Africa/Gaborone",
  AfricaHarare = "Africa/Harare",
  AfricaJohannesburg = "Africa/Johannesburg",
  AfricaJuba = "Africa/Juba",
  AfricaKampala = "Africa/Kampala",
  AfricaKhartoum = "Africa/Khartoum",
  AfricaKigali = "Africa/Kigali",
  AfricaKinshasa = "Africa/Kinshasa",
  AfricaLagos = "Africa/Lagos",
  AfricaLibreville = "Africa/Libreville",
  AfricaLome = "Africa/Lome",
  AfricaLuanda = "Africa/Luanda",
  AfricaLubumbashi = "Africa/Lubumbashi",
  AfricaLusaka = "Africa/Lusaka",
  AfricaMalabo = "Africa/Malabo",
  AfricaMaputo = "Africa/Maputo",
  AfricaMaseru = "Africa/Maseru",
  AfricaMbabane = "Africa/Mbabane",
  AfricaMogadishu = "Africa/Mogadishu",
  AfricaMonrovia = "Africa/Monrovia",
  AfricaNairobi = "Africa/Nairobi",
  AfricaNdjamena = "Africa/Ndjamena",
  AfricaNiamey = "Africa/Niamey",
  AfricaNouakchott = "Africa/Nouakchott",
  AfricaOuagadougou = "Africa/Ouagadougou",
  AfricaPortoNovo = "Africa/Porto-Novo",
  AfricaSaoTome = "Africa/Sao_Tome",
  AfricaTimbuktu = "Africa/Timbuktu",
  AfricaTripoli = "Africa/Tripoli",
  AfricaTunis = "Africa/Tunis",
  AfricaWindhoek = "Africa/Windhoek",
  AmericaAdak = "America/Adak",
  AmericaAnchorage = "America/Anchorage",
  AmericaAnguilla = "America/Anguilla",
  AmericaAntigua = "America/Antigua",
  AmericaAraguaina = "America/Araguaina",
  AmericaArgentinaBuenosAires = "America/Argentina/Buenos_Aires",
  AmericaArgentinaCatamarca = "America/Argentina/Catamarca",
  AmericaArgentinaComodRivadavia = "America/Argentina/ComodRivadavia",
  AmericaArgentinaCordoba = "America/Argentina/Cordoba",
  AmericaArgentinaJujuy = "America/Argentina/Jujuy",
  AmericaArgentinaLaRioja = "America/Argentina/La_Rioja",
  AmericaArgentinaMendoza = "America/Argentina/Mendoza",
  AmericaArgentinaRioGallegos = "America/Argentina/Rio_Gallegos",
  AmericaArgentinaSalta = "America/Argentina/Salta",
  AmericaArgentinaSanJuan = "America/Argentina/San_Juan",
  AmericaArgentinaSanLuis = "America/Argentina/San_Luis",
  AmericaArgentinaTucuman = "America/Argentina/Tucuman",
  AmericaArgentinaUshuaia = "America/Argentina/Ushuaia",
  AmericaAruba = "America/Aruba",
  AmericaAsuncion = "America/Asuncion",
  AmericaAtikokan = "America/Atikokan",
  AmericaAtka = "America/Atka",
  AmericaBahia = "America/Bahia",
  AmericaBahiaBanderas = "America/Bahia_Banderas",
  AmericaBarbados = "America/Barbados",
  AmericaBelem = "America/Belem",
  AmericaBelize = "America/Belize",
  AmericaBlancSablon = "America/Blanc-Sablon",
  AmericaBoaVista = "America/Boa_Vista",
  AmericaBogota = "America/Bogota",
  AmericaBoise = "America/Boise",
  AmericaBuenosAires = "America/Buenos_Aires",
  AmericaCambridgeBay = "America/Cambridge_Bay",
  AmericaCampoGrande = "America/Campo_Grande",
  AmericaCancun = "America/Cancun",
  AmericaCaracas = "America/Caracas",
  AmericaCatamarca = "America/Catamarca",
  AmericaCayenne = "America/Cayenne",
  AmericaCayman = "America/Cayman",
  AmericaChicago = "America/Chicago",
  AmericaChihuahua = "America/Chihuahua",
  AmericaCoralHarbour = "America/Coral_Harbour",
  AmericaCordoba = "America/Cordoba",
  AmericaCostaRica = "America/Costa_Rica",
  AmericaCreston = "America/Creston",
  AmericaCuiaba = "America/Cuiaba",
  AmericaCuracao = "America/Curacao",
  AmericaDanmarkshavn = "America/Danmarkshavn",
  AmericaDawson = "America/Dawson",
  AmericaDawsonCreek = "America/Dawson_Creek",
  AmericaDenver = "America/Denver",
  AmericaDetroit = "America/Detroit",
  AmericaDominica = "America/Dominica",
  AmericaEdmonton = "America/Edmonton",
  AmericaEirunepe = "America/Eirunepe",
  AmericaElSalvador = "America/El_Salvador",
  AmericaEnsenada = "America/Ensenada",
  AmericaFortNelson = "America/Fort_Nelson",
  AmericaFortWayne = "America/Fort_Wayne",
  AmericaFortaleza = "America/Fortaleza",
  AmericaGlaceBay = "America/Glace_Bay",
  AmericaGodthab = "America/Godthab",
  AmericaGooseBay = "America/Goose_Bay",
  AmericaGrandTurk = "America/Grand_Turk",
  AmericaGrenada = "America/Grenada",
  AmericaGuadeloupe = "America/Guadeloupe",
  AmericaGuatemala = "America/Guatemala",
  AmericaGuayaquil = "America/Guayaquil",
  AmericaGuyana = "America/Guyana",
  AmericaHalifax = "America/Halifax",
  AmericaHavana = "America/Havana",
  AmericaHermosillo = "America/Hermosillo",
  AmericaIndianaIndianapolis = "America/Indiana/Indianapolis",
  AmericaIndianaKnox = "America/Indiana/Knox",
  AmericaIndianaMarengo = "America/Indiana/Marengo",
  AmericaIndianaPetersburg = "America/Indiana/Petersburg",
  AmericaIndianaTellCity = "America/Indiana/Tell_City",
  AmericaIndianaVevay = "America/Indiana/Vevay",
  AmericaIndianaVincennes = "America/Indiana/Vincennes",
  AmericaIndianaWinamac = "America/Indiana/Winamac",
  AmericaIndianapolis = "America/Indianapolis",
  AmericaInuvik = "America/Inuvik",
  AmericaIqaluit = "America/Iqaluit",
  AmericaJamaica = "America/Jamaica",
  AmericaJujuy = "America/Jujuy",
  AmericaJuneau = "America/Juneau",
  AmericaKentuckyLouisville = "America/Kentucky/Louisville",
  AmericaKentuckyMonticello = "America/Kentucky/Monticello",
  AmericaKnoxIN = "America/Knox_IN",
  AmericaKralendijk = "America/Kralendijk",
  AmericaLaPaz = "America/La_Paz",
  AmericaLima = "America/Lima",
  AmericaLosAngeles = "America/Los_Angeles",
  AmericaLouisville = "America/Louisville",
  AmericaLowerPrinces = "America/Lower_Princes",
  AmericaMaceio = "America/Maceio",
  AmericaManagua = "America/Managua",
  AmericaManaus = "America/Manaus",
  AmericaMarigot = "America/Marigot",
  AmericaMartinique = "America/Martinique",
  AmericaMatamoros = "America/Matamoros",
  AmericaMazatlan = "America/Mazatlan",
  AmericaMendoza = "America/Mendoza",
  AmericaMenominee = "America/Menominee",
  AmericaMerida = "America/Merida",
  AmericaMetlakatla = "America/Metlakatla",
  AmericaMexicoCity = "America/Mexico_City",
  AmericaMiquelon = "America/Miquelon",
  AmericaMoncton = "America/Moncton",
  AmericaMonterrey = "America/Monterrey",
  AmericaMontevideo = "America/Montevideo",
  AmericaMontreal = "America/Montreal",
  AmericaMontserrat = "America/Montserrat",
  AmericaNassau = "America/Nassau",
  AmericaNewYork = "America/New_York",
  AmericaNipigon = "America/Nipigon",
  AmericaNome = "America/Nome",
  AmericaNoronha = "America/Noronha",
  AmericaNorthDakotaBeulah = "America/North_Dakota/Beulah",
  AmericaNorthDakotaCenter = "America/North_Dakota/Center",
  AmericaNorthDakotaNewSalem = "America/North_Dakota/New_Salem",
  AmericaNuuk = "America/Nuuk",
  AmericaOjinaga = "America/Ojinaga",
  AmericaPanama = "America/Panama",
  AmericaPangnirtung = "America/Pangnirtung",
  AmericaParamaribo = "America/Paramaribo",
  AmericaPhoenix = "America/Phoenix",
  AmericaPortauPrince = "America/Port-au-Prince",
  AmericaPortofSpain = "America/Port_of_Spain",
  AmericaPortoAcre = "America/Porto_Acre",
  AmericaPortoVelho = "America/Porto_Velho",
  AmericaPuertoRico = "America/Puerto_Rico",
  AmericaPuntaArenas = "America/Punta_Arenas",
  AmericaRainyRiver = "America/Rainy_River",
  AmericaRankinInlet = "America/Rankin_Inlet",
  AmericaRecife = "America/Recife",
  AmericaRegina = "America/Regina",
  AmericaResolute = "America/Resolute",
  AmericaRioBranco = "America/Rio_Branco",
  AmericaRosario = "America/Rosario",
  AmericaSantaIsabel = "America/Santa_Isabel",
  AmericaSantarem = "America/Santarem",
  AmericaSantiago = "America/Santiago",
  AmericaSantoDomingo = "America/Santo_Domingo",
  AmericaSaoPaulo = "America/Sao_Paulo",
  AmericaScoresbysund = "America/Scoresbysund",
  AmericaShiprock = "America/Shiprock",
  AmericaSitka = "America/Sitka",
  AmericaStBarthelemy = "America/St_Barthelemy",
  AmericaStJohns = "America/St_Johns",
  AmericaStKitts = "America/St_Kitts",
  AmericaStLucia = "America/St_Lucia",
  AmericaStThomas = "America/St_Thomas",
  AmericaStVincent = "America/St_Vincent",
  AmericaSwiftCurrent = "America/Swift_Current",
  AmericaTegucigalpa = "America/Tegucigalpa",
  AmericaThule = "America/Thule",
  AmericaThunderBay = "America/Thunder_Bay",
  AmericaTijuana = "America/Tijuana",
  AmericaToronto = "America/Toronto",
  AmericaTortola = "America/Tortola",
  AmericaVancouver = "America/Vancouver",
  AmericaVirgin = "America/Virgin",
  AmericaWhitehorse = "America/Whitehorse",
  AmericaWinnipeg = "America/Winnipeg",
  AmericaYakutat = "America/Yakutat",
  AmericaYellowknife = "America/Yellowknife",
  AntarcticaCasey = "Antarctica/Casey",
  AntarcticaDavis = "Antarctica/Davis",
  AntarcticaDumontDUrville = "Antarctica/DumontDUrville",
  AntarcticaMacquarie = "Antarctica/Macquarie",
  AntarcticaMawson = "Antarctica/Mawson",
  AntarcticaMcMurdo = "Antarctica/McMurdo",
  AntarcticaPalmer = "Antarctica/Palmer",
  AntarcticaRothera = "Antarctica/Rothera",
  AntarcticaSouthPole = "Antarctica/South_Pole",
  AntarcticaSyowa = "Antarctica/Syowa",
  AntarcticaTroll = "Antarctica/Troll",
  AntarcticaVostok = "Antarctica/Vostok",
  ArcticLongyearbyen = "Arctic/Longyearbyen",
  AsiaAden = "Asia/Aden",
  AsiaAlmaty = "Asia/Almaty",
  AsiaAmman = "Asia/Amman",
  AsiaAnadyr = "Asia/Anadyr",
  AsiaAqtau = "Asia/Aqtau",
  AsiaAqtobe = "Asia/Aqtobe",
  AsiaAshgabat = "Asia/Ashgabat",
  AsiaAshkhabad = "Asia/Ashkhabad",
  AsiaAtyrau = "Asia/Atyrau",
  AsiaBaghdad = "Asia/Baghdad",
  AsiaBahrain = "Asia/Bahrain",
  AsiaBaku = "Asia/Baku",
  AsiaBangkok = "Asia/Bangkok",
  AsiaBarnaul = "Asia/Barnaul",
  AsiaBeirut = "Asia/Beirut",
  AsiaBishkek = "Asia/Bishkek",
  AsiaBrunei = "Asia/Brunei",
  AsiaCalcutta = "Asia/Calcutta",
  AsiaChita = "Asia/Chita",
  AsiaChoibalsan = "Asia/Choibalsan",
  AsiaChongqing = "Asia/Chongqing",
  AsiaChungking = "Asia/Chungking",
  AsiaColombo = "Asia/Colombo",
  AsiaDacca = "Asia/Dacca",
  AsiaDamascus = "Asia/Damascus",
  AsiaDhaka = "Asia/Dhaka",
  AsiaDili = "Asia/Dili",
  AsiaDubai = "Asia/Dubai",
  AsiaDushanbe = "Asia/Dushanbe",
  AsiaFamagusta = "Asia/Famagusta",
  AsiaGaza = "Asia/Gaza",
  AsiaHarbin = "Asia/Harbin",
  AsiaHebron = "Asia/Hebron",
  AsiaHoChiMinh = "Asia/Ho_Chi_Minh",
  AsiaHongKong = "Asia/Hong_Kong",
  AsiaHovd = "Asia/Hovd",
  AsiaIrkutsk = "Asia/Irkutsk",
  AsiaIstanbul = "Asia/Istanbul",
  AsiaJakarta = "Asia/Jakarta",
  AsiaJayapura = "Asia/Jayapura",
  AsiaJerusalem = "Asia/Jerusalem",
  AsiaKabul = "Asia/Kabul",
  AsiaKamchatka = "Asia/Kamchatka",
  AsiaKarachi = "Asia/Karachi",
  AsiaKashgar = "Asia/Kashgar",
  AsiaKathmandu = "Asia/Kathmandu",
  AsiaKatmandu = "Asia/Katmandu",
  AsiaKhandyga = "Asia/Khandyga",
  AsiaKolkata = "Asia/Kolkata",
  AsiaKrasnoyarsk = "Asia/Krasnoyarsk",
  AsiaKualaLumpur = "Asia/Kuala_Lumpur",
  AsiaKuching = "Asia/Kuching",
  AsiaKuwait = "Asia/Kuwait",
  AsiaMacao = "Asia/Macao",
  AsiaMacau = "Asia/Macau",
  AsiaMagadan = "Asia/Magadan",
  AsiaMakassar = "Asia/Makassar",
  AsiaManila = "Asia/Manila",
  AsiaMuscat = "Asia/Muscat",
  AsiaNicosia = "Asia/Nicosia",
  AsiaNovokuznetsk = "Asia/Novokuznetsk",
  AsiaNovosibirsk = "Asia/Novosibirsk",
  AsiaOmsk = "Asia/Omsk",
  AsiaOral = "Asia/Oral",
  AsiaPhnomPenh = "Asia/Phnom_Penh",
  AsiaPontianak = "Asia/Pontianak",
  AsiaPyongyang = "Asia/Pyongyang",
  AsiaQatar = "Asia/Qatar",
  AsiaQostanay = "Asia/Qostanay",
  AsiaQyzylorda = "Asia/Qyzylorda",
  AsiaRangoon = "Asia/Rangoon",
  AsiaRiyadh = "Asia/Riyadh",
  AsiaSaigon = "Asia/Saigon",
  AsiaSakhalin = "Asia/Sakhalin",
  AsiaSamarkand = "Asia/Samarkand",
  AsiaSeoul = "Asia/Seoul",
  AsiaShanghai = "Asia/Shanghai",
  AsiaSingapore = "Asia/Singapore",
  AsiaSrednekolymsk = "Asia/Srednekolymsk",
  AsiaTaipei = "Asia/Taipei",
  AsiaTashkent = "Asia/Tashkent",
  AsiaTbilisi = "Asia/Tbilisi",
  AsiaTehran = "Asia/Tehran",
  AsiaTelAviv = "Asia/Tel_Aviv",
  AsiaThimbu = "Asia/Thimbu",
  AsiaThimphu = "Asia/Thimphu",
  AsiaTokyo = "Asia/Tokyo",
  AsiaTomsk = "Asia/Tomsk",
  AsiaUjungPandang = "Asia/Ujung_Pandang",
  AsiaUlaanbaatar = "Asia/Ulaanbaatar",
  AsiaUlanBator = "Asia/Ulan_Bator",
  AsiaUrumqi = "Asia/Urumqi",
  AsiaUstNera = "Asia/Ust-Nera",
  AsiaVientiane = "Asia/Vientiane",
  AsiaVladivostok = "Asia/Vladivostok",
  AsiaYakutsk = "Asia/Yakutsk",
  AsiaYangon = "Asia/Yangon",
  AsiaYekaterinburg = "Asia/Yekaterinburg",
  AsiaYerevan = "Asia/Yerevan",
  AtlanticAzores = "Atlantic/Azores",
  AtlanticBermuda = "Atlantic/Bermuda",
  AtlanticCanary = "Atlantic/Canary",
  AtlanticCapeVerde = "Atlantic/Cape_Verde",
  AtlanticFaeroe = "Atlantic/Faeroe",
  AtlanticFaroe = "Atlantic/Faroe",
  AtlanticJanMayen = "Atlantic/Jan_Mayen",
  AtlanticMadeira = "Atlantic/Madeira",
  AtlanticReykjavik = "Atlantic/Reykjavik",
  AtlanticSouthGeorgia = "Atlantic/South_Georgia",
  AtlanticStHelena = "Atlantic/St_Helena",
  AtlanticStanley = "Atlantic/Stanley",
  AustraliaACT = "Australia/ACT",
  AustraliaAdelaide = "Australia/Adelaide",
  AustraliaBrisbane = "Australia/Brisbane",
  AustraliaBrokenHill = "Australia/Broken_Hill",
  AustraliaCanberra = "Australia/Canberra",
  AustraliaCurrie = "Australia/Currie",
  AustraliaDarwin = "Australia/Darwin",
  AustraliaEucla = "Australia/Eucla",
  AustraliaHobart = "Australia/Hobart",
  AustraliaLHI = "Australia/LHI",
  AustraliaLindeman = "Australia/Lindeman",
  AustraliaLordHowe = "Australia/Lord_Howe",
  AustraliaMelbourne = "Australia/Melbourne",
  AustraliaNSW = "Australia/NSW",
  AustraliaNorth = "Australia/North",
  AustraliaPerth = "Australia/Perth",
  AustraliaQueensland = "Australia/Queensland",
  AustraliaSouth = "Australia/South",
  AustraliaSydney = "Australia/Sydney",
  AustraliaTasmania = "Australia/Tasmania",
  AustraliaVictoria = "Australia/Victoria",
  AustraliaWest = "Australia/West",
  AustraliaYancowinna = "Australia/Yancowinna",
  BrazilAcre = "Brazil/Acre",
  BrazilDeNoronha = "Brazil/DeNoronha",
  BrazilEast = "Brazil/East",
  BrazilWest = "Brazil/West",
  CET = "CET",
  CST6CDT = "CST6CDT",
  CanadaAtlantic = "Canada/Atlantic",
  CanadaCentral = "Canada/Central",
  CanadaEastern = "Canada/Eastern",
  CanadaMountain = "Canada/Mountain",
  CanadaNewfoundland = "Canada/Newfoundland",
  CanadaPacific = "Canada/Pacific",
  CanadaSaskatchewan = "Canada/Saskatchewan",
  CanadaYukon = "Canada/Yukon",
  ChileContinental = "Chile/Continental",
  ChileEasterIsland = "Chile/EasterIsland",
  Cuba = "Cuba",
  EET = "EET",
  EST = "EST",
  EST5EDT = "EST5EDT",
  Egypt = "Egypt",
  Eire = "Eire",
  EtcGMT = "Etc/GMT",
  EtcGMTPlus0 = "Etc/GMT+0",
  EtcGMTPlus1 = "Etc/GMT+1",
  EtcGMTPlus10 = "Etc/GMT+10",
  EtcGMTPlus11 = "Etc/GMT+11",
  EtcGMTPlus12 = "Etc/GMT+12",
  EtcGMTPlus2 = "Etc/GMT+2",
  EtcGMTPlus3 = "Etc/GMT+3",
  EtcGMTPlus4 = "Etc/GMT+4",
  EtcGMTPlus5 = "Etc/GMT+5",
  EtcGMTPlus6 = "Etc/GMT+6",
  EtcGMTPlus7 = "Etc/GMT+7",
  EtcGMTPlus8 = "Etc/GMT+8",
  EtcGMTPlus9 = "Etc/GMT+9",
  EtcGMTMinus0 = "Etc/GMT-0",
  EtcGMTMinus1 = "Etc/GMT-1",
  EtcGMTMinus10 = "Etc/GMT-10",
  EtcGMTMinus11 = "Etc/GMT-11",
  EtcGMTMinus12 = "Etc/GMT-12",
  EtcGMTMinus13 = "Etc/GMT-13",
  EtcGMTMinus14 = "Etc/GMT-14",
  EtcGMTMinus2 = "Etc/GMT-2",
  EtcGMTMinus3 = "Etc/GMT-3",
  EtcGMTMinus4 = "Etc/GMT-4",
  EtcGMTMinus5 = "Etc/GMT-5",
  EtcGMTMinus6 = "Etc/GMT-6",
  EtcGMTMinus7 = "Etc/GMT-7",
  EtcGMTMinus8 = "Etc/GMT-8",
  EtcGMTMinus9 = "Etc/GMT-9",
  EtcGMT0 = "Etc/GMT0",
  EtcGreenwich = "Etc/Greenwich",
  EtcUCT = "Etc/UCT",
  EtcUTC = "Etc/UTC",
  EtcUniversal = "Etc/Universal",
  EtcZulu = "Etc/Zulu",
  EuropeAmsterdam = "Europe/Amsterdam",
  EuropeAndorra = "Europe/Andorra",
  EuropeAstrakhan = "Europe/Astrakhan",
  EuropeAthens = "Europe/Athens",
  EuropeBelfast = "Europe/Belfast",
  EuropeBelgrade = "Europe/Belgrade",
  EuropeBerlin = "Europe/Berlin",
  EuropeBratislava = "Europe/Bratislava",
  EuropeBrussels = "Europe/Brussels",
  EuropeBucharest = "Europe/Bucharest",
  EuropeBudapest = "Europe/Budapest",
  EuropeBusingen = "Europe/Busingen",
  EuropeChisinau = "Europe/Chisinau",
  EuropeCopenhagen = "Europe/Copenhagen",
  EuropeDublin = "Europe/Dublin",
  EuropeGibraltar = "Europe/Gibraltar",
  EuropeGuernsey = "Europe/Guernsey",
  EuropeHelsinki = "Europe/Helsinki",
  EuropeIsleofMan = "Europe/Isle_of_Man",
  EuropeIstanbul = "Europe/Istanbul",
  EuropeJersey = "Europe/Jersey",
  EuropeKaliningrad = "Europe/Kaliningrad",
  EuropeKiev = "Europe/Kiev",
  EuropeKirov = "Europe/Kirov",
  EuropeLisbon = "Europe/Lisbon",
  EuropeLjubljana = "Europe/Ljubljana",
  EuropeLondon = "Europe/London",
  EuropeLuxembourg = "Europe/Luxembourg",
  EuropeMadrid = "Europe/Madrid",
  EuropeMalta = "Europe/Malta",
  EuropeMariehamn = "Europe/Mariehamn",
  EuropeMinsk = "Europe/Minsk",
  EuropeMonaco = "Europe/Monaco",
  EuropeMoscow = "Europe/Moscow",
  EuropeNicosia = "Europe/Nicosia",
  EuropeOslo = "Europe/Oslo",
  EuropeParis = "Europe/Paris",
  EuropePodgorica = "Europe/Podgorica",
  EuropePrague = "Europe/Prague",
  EuropeRiga = "Europe/Riga",
  EuropeRome = "Europe/Rome",
  EuropeSamara = "Europe/Samara",
  EuropeSanMarino = "Europe/San_Marino",
  EuropeSarajevo = "Europe/Sarajevo",
  EuropeSaratov = "Europe/Saratov",
  EuropeSimferopol = "Europe/Simferopol",
  EuropeSkopje = "Europe/Skopje",
  EuropeSofia = "Europe/Sofia",
  EuropeStockholm = "Europe/Stockholm",
  EuropeTallinn = "Europe/Tallinn",
  EuropeTirane = "Europe/Tirane",
  EuropeTiraspol = "Europe/Tiraspol",
  EuropeUlyanovsk = "Europe/Ulyanovsk",
  EuropeUzhgorod = "Europe/Uzhgorod",
  EuropeVaduz = "Europe/Vaduz",
  EuropeVatican = "Europe/Vatican",
  EuropeVienna = "Europe/Vienna",
  EuropeVilnius = "Europe/Vilnius",
  EuropeVolgograd = "Europe/Volgograd",
  EuropeWarsaw = "Europe/Warsaw",
  EuropeZagreb = "Europe/Zagreb",
  EuropeZaporozhye = "Europe/Zaporozhye",
  EuropeZurich = "Europe/Zurich",
  GB = "GB",
  GBEire = "GB-Eire",
  GMT = "GMT",
  GMTPlus0 = "GMT+0",
  GMTMinus0 = "GMT-0",
  GMT0 = "GMT0",
  Greenwich = "Greenwich",
  HST = "HST",
  Hongkong = "Hongkong",
  Iceland = "Iceland",
  IndianAntananarivo = "Indian/Antananarivo",
  IndianChagos = "Indian/Chagos",
  IndianChristmas = "Indian/Christmas",
  IndianCocos = "Indian/Cocos",
  IndianComoro = "Indian/Comoro",
  IndianKerguelen = "Indian/Kerguelen",
  IndianMahe = "Indian/Mahe",
  IndianMaldives = "Indian/Maldives",
  IndianMauritius = "Indian/Mauritius",
  IndianMayotte = "Indian/Mayotte",
  IndianReunion = "Indian/Reunion",
  Iran = "Iran",
  Israel = "Israel",
  Jamaica = "Jamaica",
  Japan = "Japan",
  Kwajalein = "Kwajalein",
  Libya = "Libya",
  MET = "MET",
  MST = "MST",
  MST7MDT = "MST7MDT",
  MexicoBajaNorte = "Mexico/BajaNorte",
  MexicoBajaSur = "Mexico/BajaSur",
  MexicoGeneral = "Mexico/General",
  NZ = "NZ",
  NZCHAT = "NZ-CHAT",
  Navajo = "Navajo",
  PRC = "PRC",
  PST8PDT = "PST8PDT",
  PacificApia = "Pacific/Apia",
  PacificAuckland = "Pacific/Auckland",
  PacificBougainville = "Pacific/Bougainville",
  PacificChatham = "Pacific/Chatham",
  PacificChuuk = "Pacific/Chuuk",
  PacificEaster = "Pacific/Easter",
  PacificEfate = "Pacific/Efate",
  PacificEnderbury = "Pacific/Enderbury",
  PacificFakaofo = "Pacific/Fakaofo",
  PacificFiji = "Pacific/Fiji",
  PacificFunafuti = "Pacific/Funafuti",
  PacificGalapagos = "Pacific/Galapagos",
  PacificGambier = "Pacific/Gambier",
  PacificGuadalcanal = "Pacific/Guadalcanal",
  PacificGuam = "Pacific/Guam",
  PacificHonolulu = "Pacific/Honolulu",
  PacificJohnston = "Pacific/Johnston",
  PacificKiritimati = "Pacific/Kiritimati",
  PacificKosrae = "Pacific/Kosrae",
  PacificKwajalein = "Pacific/Kwajalein",
  PacificMajuro = "Pacific/Majuro",
  PacificMarquesas = "Pacific/Marquesas",
  PacificMidway = "Pacific/Midway",
  PacificNauru = "Pacific/Nauru",
  PacificNiue = "Pacific/Niue",
  PacificNorfolk = "Pacific/Norfolk",
  PacificNoumea = "Pacific/Noumea",
  PacificPagoPago = "Pacific/Pago_Pago",
  PacificPalau = "Pacific/Palau",
  PacificPitcairn = "Pacific/Pitcairn",
  PacificPohnpei = "Pacific/Pohnpei",
  PacificPonape = "Pacific/Ponape",
  PacificPortMoresby = "Pacific/Port_Moresby",
  PacificRarotonga = "Pacific/Rarotonga",
  PacificSaipan = "Pacific/Saipan",
  PacificSamoa = "Pacific/Samoa",
  PacificTahiti = "Pacific/Tahiti",
  PacificTarawa = "Pacific/Tarawa",
  PacificTongatapu = "Pacific/Tongatapu",
  PacificTruk = "Pacific/Truk",
  PacificWake = "Pacific/Wake",
  PacificWallis = "Pacific/Wallis",
  PacificYap = "Pacific/Yap",
  Poland = "Poland",
  Portugal = "Portugal",
  ROC = "ROC",
  ROK = "ROK",
  Singapore = "Singapore",
  Turkey = "Turkey",
  UCT = "UCT",
  USAlaska = "US/Alaska",
  USAleutian = "US/Aleutian",
  USArizona = "US/Arizona",
  USCentral = "US/Central",
  USEastIndiana = "US/East-Indiana",
  USEastern = "US/Eastern",
  USHawaii = "US/Hawaii",
  USIndianaStarke = "US/Indiana-Starke",
  USMichigan = "US/Michigan",
  USMountain = "US/Mountain",
  USPacific = "US/Pacific",
  USPacificNew = "US/Pacific-New",
  USSamoa = "US/Samoa",
  UTC = "UTC",
  Universal = "Universal",
  WSU = "W-SU",
  WET = "WET",
  Zulu = "Zulu"
}
