// Generated at: 2020-09-10T15:15:50.429Z

export const timezones = [
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmara",
  "Africa/Asmera",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Timbuktu",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca",
  "America/Argentina/ComodRivadavia",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Atikokan",
  "America/Atka",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Buenos_Aires",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Catamarca",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Coral_Harbour",
  "America/Cordoba",
  "America/Costa_Rica",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Ensenada",
  "America/Fort_Nelson",
  "America/Fort_Wayne",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Indianapolis",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Jujuy",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/Knox_IN",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Louisville",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Mendoza",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montreal",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Nuuk",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Porto_Acre",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Punta_Arenas",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Rosario",
  "America/Santa_Isabel",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Shiprock",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Virgin",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/South_Pole",
  "Antarctica/Syowa",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Ashkhabad",
  "Asia/Atyrau",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Calcutta",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Chongqing",
  "Asia/Chungking",
  "Asia/Colombo",
  "Asia/Dacca",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Harbin",
  "Asia/Hebron",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Istanbul",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kashgar",
  "Asia/Kathmandu",
  "Asia/Katmandu",
  "Asia/Khandyga",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macao",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qostanay",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Saigon",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Tel_Aviv",
  "Asia/Thimbu",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ujung_Pandang",
  "Asia/Ulaanbaatar",
  "Asia/Ulan_Bator",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yangon",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faeroe",
  "Atlantic/Faroe",
  "Atlantic/Jan_Mayen",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/ACT",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Canberra",
  "Australia/Currie",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/LHI",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/NSW",
  "Australia/North",
  "Australia/Perth",
  "Australia/Queensland",
  "Australia/South",
  "Australia/Sydney",
  "Australia/Tasmania",
  "Australia/Victoria",
  "Australia/West",
  "Australia/Yancowinna",
  "Brazil/Acre",
  "Brazil/DeNoronha",
  "Brazil/East",
  "Brazil/West",
  "CET",
  "CST6CDT",
  "Canada/Atlantic",
  "Canada/Central",
  "Canada/Eastern",
  "Canada/Mountain",
  "Canada/Newfoundland",
  "Canada/Pacific",
  "Canada/Saskatchewan",
  "Canada/Yukon",
  "Chile/Continental",
  "Chile/EasterIsland",
  "Cuba",
  "EET",
  "EST",
  "EST5EDT",
  "Egypt",
  "Eire",
  "Etc/GMT",
  "Etc/GMT+0",
  "Etc/GMT+1",
  "Etc/GMT+10",
  "Etc/GMT+11",
  "Etc/GMT+12",
  "Etc/GMT+2",
  "Etc/GMT+3",
  "Etc/GMT+4",
  "Etc/GMT+5",
  "Etc/GMT+6",
  "Etc/GMT+7",
  "Etc/GMT+8",
  "Etc/GMT+9",
  "Etc/GMT-0",
  "Etc/GMT-1",
  "Etc/GMT-10",
  "Etc/GMT-11",
  "Etc/GMT-12",
  "Etc/GMT-13",
  "Etc/GMT-14",
  "Etc/GMT-2",
  "Etc/GMT-3",
  "Etc/GMT-4",
  "Etc/GMT-5",
  "Etc/GMT-6",
  "Etc/GMT-7",
  "Etc/GMT-8",
  "Etc/GMT-9",
  "Etc/GMT0",
  "Etc/Greenwich",
  "Etc/UCT",
  "Etc/UTC",
  "Etc/Universal",
  "Etc/Zulu",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belfast",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Nicosia",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Tiraspol",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "GB",
  "GB-Eire",
  "GMT",
  "GMT+0",
  "GMT-0",
  "GMT0",
  "Greenwich",
  "HST",
  "Hongkong",
  "Iceland",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Iran",
  "Israel",
  "Jamaica",
  "Japan",
  "Kwajalein",
  "Libya",
  "MET",
  "MST",
  "MST7MDT",
  "Mexico/BajaNorte",
  "Mexico/BajaSur",
  "Mexico/General",
  "NZ",
  "NZ-CHAT",
  "Navajo",
  "PRC",
  "PST8PDT",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Ponape",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Samoa",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Truk",
  "Pacific/Wake",
  "Pacific/Wallis",
  "Pacific/Yap",
  "Poland",
  "Portugal",
  "ROC",
  "ROK",
  "Singapore",
  "Turkey",
  "UCT",
  "US/Alaska",
  "US/Aleutian",
  "US/Arizona",
  "US/Central",
  "US/East-Indiana",
  "US/Eastern",
  "US/Hawaii",
  "US/Indiana-Starke",
  "US/Michigan",
  "US/Mountain",
  "US/Pacific",
  "US/Pacific-New",
  "US/Samoa",
  "UTC",
  "Universal",
  "W-SU",
  "WET",
  "Zulu",
];

export enum Timezone {
  AfricaAbidjan = "Africa/Abidjan",
  AfricaAccra = "Africa/Accra",
  AfricaAddisAbaba = "Africa/Addis_Ababa",
  AfricaAlgiers = "Africa/Algiers",
  AfricaAsmara = "Africa/Asmara",
  AfricaAsmera = "Africa/Asmera",
  AfricaBamako = "Africa/Bamako",
  AfricaBangui = "Africa/Bangui",
  AfricaBanjul = "Africa/Banjul",
  AfricaBissau = "Africa/Bissau",
  AfricaBlantyre = "Africa/Blantyre",
  AfricaBrazzaville = "Africa/Brazzaville",
  AfricaBujumbura = "Africa/Bujumbura",
  AfricaCairo = "Africa/Cairo",
  AfricaCasablanca = "Africa/Casablanca",
  AfricaCeuta = "Africa/Ceuta",
  AfricaConakry = "Africa/Conakry",
  AfricaDakar = "Africa/Dakar",
  AfricaDaresSalaam = "Africa/Dar_es_Salaam",
  AfricaDjibouti = "Africa/Djibouti",
  AfricaDouala = "Africa/Douala",
  AfricaElAaiun = "Africa/El_Aaiun",
  AfricaFreetown = "Africa/Freetown",
  AfricaGaborone = "Africa/Gaborone",
  AfricaHarare = "Africa/Harare",
  AfricaJohannesburg = "Africa/Johannesburg",
  AfricaJuba = "Africa/Juba",
  AfricaKampala = "Africa/Kampala",
  AfricaKhartoum = "Africa/Khartoum",
  AfricaKigali = "Africa/Kigali",
  AfricaKinshasa = "Africa/Kinshasa",
  AfricaLagos = "Africa/Lagos",
  AfricaLibreville = "Africa/Libreville",
  AfricaLome = "Africa/Lome",
  AfricaLuanda = "Africa/Luanda",
  AfricaLubumbashi = "Africa/Lubumbashi",
  AfricaLusaka = "Africa/Lusaka",
  AfricaMalabo = "Africa/Malabo",
  AfricaMaputo = "Africa/Maputo",
  AfricaMaseru = "Africa/Maseru",
  AfricaMbabane = "Africa/Mbabane",
  AfricaMogadishu = "Africa/Mogadishu",
  AfricaMonrovia = "Africa/Monrovia",
  AfricaNairobi = "Africa/Nairobi",
  AfricaNdjamena = "Africa/Ndjamena",
  AfricaNiamey = "Africa/Niamey",
  AfricaNouakchott = "Africa/Nouakchott",
  AfricaOuagadougou = "Africa/Ouagadougou",
  AfricaPortoNovo = "Africa/Porto-Novo",
  AfricaSaoTome = "Africa/Sao_Tome",
  AfricaTimbuktu = "Africa/Timbuktu",
  AfricaTripoli = "Africa/Tripoli",
  AfricaTunis = "Africa/Tunis",
  AfricaWindhoek = "Africa/Windhoek",
  AmericaAdak = "America/Adak",
  AmericaAnchorage = "America/Anchorage",
  AmericaAnguilla = "America/Anguilla",
  AmericaAntigua = "America/Antigua",
  AmericaAraguaina = "America/Araguaina",
  AmericaArgentinaBuenosAires = "America/Argentina/Buenos_Aires",
  AmericaArgentinaCatamarca = "America/Argentina/Catamarca",
  AmericaArgentinaComodRivadavia = "America/Argentina/ComodRivadavia",
  AmericaArgentinaCordoba = "America/Argentina/Cordoba",
  AmericaArgentinaJujuy = "America/Argentina/Jujuy",
  AmericaArgentinaLaRioja = "America/Argentina/La_Rioja",
  AmericaArgentinaMendoza = "America/Argentina/Mendoza",
  AmericaArgentinaRioGallegos = "America/Argentina/Rio_Gallegos",
  AmericaArgentinaSalta = "America/Argentina/Salta",
  AmericaArgentinaSanJuan = "America/Argentina/San_Juan",
  AmericaArgentinaSanLuis = "America/Argentina/San_Luis",
  AmericaArgentinaTucuman = "America/Argentina/Tucuman",
  AmericaArgentinaUshuaia = "America/Argentina/Ushuaia",
  AmericaAruba = "America/Aruba",
  AmericaAsuncion = "America/Asuncion",
  AmericaAtikokan = "America/Atikokan",
  AmericaAtka = "America/Atka",
  AmericaBahia = "America/Bahia",
  AmericaBahiaBanderas = "America/Bahia_Banderas",
  AmericaBarbados = "America/Barbados",
  AmericaBelem = "America/Belem",
  AmericaBelize = "America/Belize",
  AmericaBlancSablon = "America/Blanc-Sablon",
  AmericaBoaVista = "America/Boa_Vista",
  AmericaBogota = "America/Bogota",
  AmericaBoise = "America/Boise",
  AmericaBuenosAires = "America/Buenos_Aires",
  AmericaCambridgeBay = "America/Cambridge_Bay",
  AmericaCampoGrande = "America/Campo_Grande",
  AmericaCancun = "America/Cancun",
  AmericaCaracas = "America/Caracas",
  AmericaCatamarca = "America/Catamarca",
  AmericaCayenne = "America/Cayenne",
  AmericaCayman = "America/Cayman",
  AmericaChicago = "America/Chicago",
  AmericaChihuahua = "America/Chihuahua",
  AmericaCoralHarbour = "America/Coral_Harbour",
  AmericaCordoba = "America/Cordoba",
  AmericaCostaRica = "America/Costa_Rica",
  AmericaCreston = "America/Creston",
  AmericaCuiaba = "America/Cuiaba",
  AmericaCuracao = "America/Curacao",
  AmericaDanmarkshavn = "America/Danmarkshavn",
  AmericaDawson = "America/Dawson",
  AmericaDawsonCreek = "America/Dawson_Creek",
  AmericaDenver = "America/Denver",
  AmericaDetroit = "America/Detroit",
  AmericaDominica = "America/Dominica",
  AmericaEdmonton = "America/Edmonton",
  AmericaEirunepe = "America/Eirunepe",
  AmericaElSalvador = "America/El_Salvador",
  AmericaEnsenada = "America/Ensenada",
  AmericaFortNelson = "America/Fort_Nelson",
  AmericaFortWayne = "America/Fort_Wayne",
  AmericaFortaleza = "America/Fortaleza",
  AmericaGlaceBay = "America/Glace_Bay",
  AmericaGodthab = "America/Godthab",
  AmericaGooseBay = "America/Goose_Bay",
  AmericaGrandTurk = "America/Grand_Turk",
  AmericaGrenada = "America/Grenada",
  AmericaGuadeloupe = "America/Guadeloupe",
  AmericaGuatemala = "America/Guatemala",
  AmericaGuayaquil = "America/Guayaquil",
  AmericaGuyana = "America/Guyana",
  AmericaHalifax = "America/Halifax",
  AmericaHavana = "America/Havana",
  AmericaHermosillo = "America/Hermosillo",
  AmericaIndianaIndianapolis = "America/Indiana/Indianapolis",
  AmericaIndianaKnox = "America/Indiana/Knox",
  AmericaIndianaMarengo = "America/Indiana/Marengo",
  AmericaIndianaPetersburg = "America/Indiana/Petersburg",
  AmericaIndianaTellCity = "America/Indiana/Tell_City",
  AmericaIndianaVevay = "America/Indiana/Vevay",
  AmericaIndianaVincennes = "America/Indiana/Vincennes",
  AmericaIndianaWinamac = "America/Indiana/Winamac",
  AmericaIndianapolis = "America/Indianapolis",
  AmericaInuvik = "America/Inuvik",
  AmericaIqaluit = "America/Iqaluit",
  AmericaJamaica = "America/Jamaica",
  AmericaJujuy = "America/Jujuy",
  AmericaJuneau = "America/Juneau",
  AmericaKentuckyLouisville = "America/Kentucky/Louisville",
  AmericaKentuckyMonticello = "America/Kentucky/Monticello",
  AmericaKnoxIN = "America/Knox_IN",
  AmericaKralendijk = "America/Kralendijk",
  AmericaLaPaz = "America/La_Paz",
  AmericaLima = "America/Lima",
  AmericaLosAngeles = "America/Los_Angeles",
  AmericaLouisville = "America/Louisville",
  AmericaLowerPrinces = "America/Lower_Princes",
  AmericaMaceio = "America/Maceio",
  AmericaManagua = "America/Managua",
  AmericaManaus = "America/Manaus",
  AmericaMarigot = "America/Marigot",
  AmericaMartinique = "America/Martinique",
  AmericaMatamoros = "America/Matamoros",
  AmericaMazatlan = "America/Mazatlan",
  AmericaMendoza = "America/Mendoza",
  AmericaMenominee = "America/Menominee",
  AmericaMerida = "America/Merida",
  AmericaMetlakatla = "America/Metlakatla",
  AmericaMexicoCity = "America/Mexico_City",
  AmericaMiquelon = "America/Miquelon",
  AmericaMoncton = "America/Moncton",
  AmericaMonterrey = "America/Monterrey",
  AmericaMontevideo = "America/Montevideo",
  AmericaMontreal = "America/Montreal",
  AmericaMontserrat = "America/Montserrat",
  AmericaNassau = "America/Nassau",
  AmericaNewYork = "America/New_York",
  AmericaNipigon = "America/Nipigon",
  AmericaNome = "America/Nome",
  AmericaNoronha = "America/Noronha",
  AmericaNorthDakotaBeulah = "America/North_Dakota/Beulah",
  AmericaNorthDakotaCenter = "America/North_Dakota/Center",
  AmericaNorthDakotaNewSalem = "America/North_Dakota/New_Salem",
  AmericaNuuk = "America/Nuuk",
  AmericaOjinaga = "America/Ojinaga",
  AmericaPanama = "America/Panama",
  AmericaPangnirtung = "America/Pangnirtung",
  AmericaParamaribo = "America/Paramaribo",
  AmericaPhoenix = "America/Phoenix",
  AmericaPortauPrince = "America/Port-au-Prince",
  AmericaPortofSpain = "America/Port_of_Spain",
  AmericaPortoAcre = "America/Porto_Acre",
  AmericaPortoVelho = "America/Porto_Velho",
  AmericaPuertoRico = "America/Puerto_Rico",
  AmericaPuntaArenas = "America/Punta_Arenas",
  AmericaRainyRiver = "America/Rainy_River",
  AmericaRankinInlet = "America/Rankin_Inlet",
  AmericaRecife = "America/Recife",
  AmericaRegina = "America/Regina",
  AmericaResolute = "America/Resolute",
  AmericaRioBranco = "America/Rio_Branco",
  AmericaRosario = "America/Rosario",
  AmericaSantaIsabel = "America/Santa_Isabel",
  AmericaSantarem = "America/Santarem",
  AmericaSantiago = "America/Santiago",
  AmericaSantoDomingo = "America/Santo_Domingo",
  AmericaSaoPaulo = "America/Sao_Paulo",
  AmericaScoresbysund = "America/Scoresbysund",
  AmericaShiprock = "America/Shiprock",
  AmericaSitka = "America/Sitka",
  AmericaStBarthelemy = "America/St_Barthelemy",
  AmericaStJohns = "America/St_Johns",
  AmericaStKitts = "America/St_Kitts",
  AmericaStLucia = "America/St_Lucia",
  AmericaStThomas = "America/St_Thomas",
  AmericaStVincent = "America/St_Vincent",
  AmericaSwiftCurrent = "America/Swift_Current",
  AmericaTegucigalpa = "America/Tegucigalpa",
  AmericaThule = "America/Thule",
  AmericaThunderBay = "America/Thunder_Bay",
  AmericaTijuana = "America/Tijuana",
  AmericaToronto = "America/Toronto",
  AmericaTortola = "America/Tortola",
  AmericaVancouver = "America/Vancouver",
  AmericaVirgin = "America/Virgin",
  AmericaWhitehorse = "America/Whitehorse",
  AmericaWinnipeg = "America/Winnipeg",
  AmericaYakutat = "America/Yakutat",
  AmericaYellowknife = "America/Yellowknife",
  AntarcticaCasey = "Antarctica/Casey",
  AntarcticaDavis = "Antarctica/Davis",
  AntarcticaDumontDUrville = "Antarctica/DumontDUrville",
  AntarcticaMacquarie = "Antarctica/Macquarie",
  AntarcticaMawson = "Antarctica/Mawson",
  AntarcticaMcMurdo = "Antarctica/McMurdo",
  AntarcticaPalmer = "Antarctica/Palmer",
  AntarcticaRothera = "Antarctica/Rothera",
  AntarcticaSouthPole = "Antarctica/South_Pole",
  AntarcticaSyowa = "Antarctica/Syowa",
  AntarcticaTroll = "Antarctica/Troll",
  AntarcticaVostok = "Antarctica/Vostok",
  ArcticLongyearbyen = "Arctic/Longyearbyen",
  AsiaAden = "Asia/Aden",
  AsiaAlmaty = "Asia/Almaty",
  AsiaAmman = "Asia/Amman",
  AsiaAnadyr = "Asia/Anadyr",
  AsiaAqtau = "Asia/Aqtau",
  AsiaAqtobe = "Asia/Aqtobe",
  AsiaAshgabat = "Asia/Ashgabat",
  AsiaAshkhabad = "Asia/Ashkhabad",
  AsiaAtyrau = "Asia/Atyrau",
  AsiaBaghdad = "Asia/Baghdad",
  AsiaBahrain = "Asia/Bahrain",
  AsiaBaku = "Asia/Baku",
  AsiaBangkok = "Asia/Bangkok",
  AsiaBarnaul = "Asia/Barnaul",
  AsiaBeirut = "Asia/Beirut",
  AsiaBishkek = "Asia/Bishkek",
  AsiaBrunei = "Asia/Brunei",
  AsiaCalcutta = "Asia/Calcutta",
  AsiaChita = "Asia/Chita",
  AsiaChoibalsan = "Asia/Choibalsan",
  AsiaChongqing = "Asia/Chongqing",
  AsiaChungking = "Asia/Chungking",
  AsiaColombo = "Asia/Colombo",
  AsiaDacca = "Asia/Dacca",
  AsiaDamascus = "Asia/Damascus",
  AsiaDhaka = "Asia/Dhaka",
  AsiaDili = "Asia/Dili",
  AsiaDubai = "Asia/Dubai",
  AsiaDushanbe = "Asia/Dushanbe",
  AsiaFamagusta = "Asia/Famagusta",
  AsiaGaza = "Asia/Gaza",
  AsiaHarbin = "Asia/Harbin",
  AsiaHebron = "Asia/Hebron",
  AsiaHoChiMinh = "Asia/Ho_Chi_Minh",
  AsiaHongKong = "Asia/Hong_Kong",
  AsiaHovd = "Asia/Hovd",
  AsiaIrkutsk = "Asia/Irkutsk",
  AsiaIstanbul = "Asia/Istanbul",
  AsiaJakarta = "Asia/Jakarta",
  AsiaJayapura = "Asia/Jayapura",
  AsiaJerusalem = "Asia/Jerusalem",
  AsiaKabul = "Asia/Kabul",
  AsiaKamchatka = "Asia/Kamchatka",
  AsiaKarachi = "Asia/Karachi",
  AsiaKashgar = "Asia/Kashgar",
  AsiaKathmandu = "Asia/Kathmandu",
  AsiaKatmandu = "Asia/Katmandu",
  AsiaKhandyga = "Asia/Khandyga",
  AsiaKolkata = "Asia/Kolkata",
  AsiaKrasnoyarsk = "Asia/Krasnoyarsk",
  AsiaKualaLumpur = "Asia/Kuala_Lumpur",
  AsiaKuching = "Asia/Kuching",
  AsiaKuwait = "Asia/Kuwait",
  AsiaMacao = "Asia/Macao",
  AsiaMacau = "Asia/Macau",
  AsiaMagadan = "Asia/Magadan",
  AsiaMakassar = "Asia/Makassar",
  AsiaManila = "Asia/Manila",
  AsiaMuscat = "Asia/Muscat",
  AsiaNicosia = "Asia/Nicosia",
  AsiaNovokuznetsk = "Asia/Novokuznetsk",
  AsiaNovosibirsk = "Asia/Novosibirsk",
  AsiaOmsk = "Asia/Omsk",
  AsiaOral = "Asia/Oral",
  AsiaPhnomPenh = "Asia/Phnom_Penh",
  AsiaPontianak = "Asia/Pontianak",
  AsiaPyongyang = "Asia/Pyongyang",
  AsiaQatar = "Asia/Qatar",
  AsiaQostanay = "Asia/Qostanay",
  AsiaQyzylorda = "Asia/Qyzylorda",
  AsiaRangoon = "Asia/Rangoon",
  AsiaRiyadh = "Asia/Riyadh",
  AsiaSaigon = "Asia/Saigon",
  AsiaSakhalin = "Asia/Sakhalin",
  AsiaSamarkand = "Asia/Samarkand",
  AsiaSeoul = "Asia/Seoul",
  AsiaShanghai = "Asia/Shanghai",
  AsiaSingapore = "Asia/Singapore",
  AsiaSrednekolymsk = "Asia/Srednekolymsk",
  AsiaTaipei = "Asia/Taipei",
  AsiaTashkent = "Asia/Tashkent",
  AsiaTbilisi = "Asia/Tbilisi",
  AsiaTehran = "Asia/Tehran",
  AsiaTelAviv = "Asia/Tel_Aviv",
  AsiaThimbu = "Asia/Thimbu",
  AsiaThimphu = "Asia/Thimphu",
  AsiaTokyo = "Asia/Tokyo",
  AsiaTomsk = "Asia/Tomsk",
  AsiaUjungPandang = "Asia/Ujung_Pandang",
  AsiaUlaanbaatar = "Asia/Ulaanbaatar",
  AsiaUlanBator = "Asia/Ulan_Bator",
  AsiaUrumqi = "Asia/Urumqi",
  AsiaUstNera = "Asia/Ust-Nera",
  AsiaVientiane = "Asia/Vientiane",
  AsiaVladivostok = "Asia/Vladivostok",
  AsiaYakutsk = "Asia/Yakutsk",
  AsiaYangon = "Asia/Yangon",
  AsiaYekaterinburg = "Asia/Yekaterinburg",
  AsiaYerevan = "Asia/Yerevan",
  AtlanticAzores = "Atlantic/Azores",
  AtlanticBermuda = "Atlantic/Bermuda",
  AtlanticCanary = "Atlantic/Canary",
  AtlanticCapeVerde = "Atlantic/Cape_Verde",
  AtlanticFaeroe = "Atlantic/Faeroe",
  AtlanticFaroe = "Atlantic/Faroe",
  AtlanticJanMayen = "Atlantic/Jan_Mayen",
  AtlanticMadeira = "Atlantic/Madeira",
  AtlanticReykjavik = "Atlantic/Reykjavik",
  AtlanticSouthGeorgia = "Atlantic/South_Georgia",
  AtlanticStHelena = "Atlantic/St_Helena",
  AtlanticStanley = "Atlantic/Stanley",
  AustraliaACT = "Australia/ACT",
  AustraliaAdelaide = "Australia/Adelaide",
  AustraliaBrisbane = "Australia/Brisbane",
  AustraliaBrokenHill = "Australia/Broken_Hill",
  AustraliaCanberra = "Australia/Canberra",
  AustraliaCurrie = "Australia/Currie",
  AustraliaDarwin = "Australia/Darwin",
  AustraliaEucla = "Australia/Eucla",
  AustraliaHobart = "Australia/Hobart",
  AustraliaLHI = "Australia/LHI",
  AustraliaLindeman = "Australia/Lindeman",
  AustraliaLordHowe = "Australia/Lord_Howe",
  AustraliaMelbourne = "Australia/Melbourne",
  AustraliaNSW = "Australia/NSW",
  AustraliaNorth = "Australia/North",
  AustraliaPerth = "Australia/Perth",
  AustraliaQueensland = "Australia/Queensland",
  AustraliaSouth = "Australia/South",
  AustraliaSydney = "Australia/Sydney",
  AustraliaTasmania = "Australia/Tasmania",
  AustraliaVictoria = "Australia/Victoria",
  AustraliaWest = "Australia/West",
  AustraliaYancowinna = "Australia/Yancowinna",
  BrazilAcre = "Brazil/Acre",
  BrazilDeNoronha = "Brazil/DeNoronha",
  BrazilEast = "Brazil/East",
  BrazilWest = "Brazil/West",
  CET = "CET",
  CST6CDT = "CST6CDT",
  CanadaAtlantic = "Canada/Atlantic",
  CanadaCentral = "Canada/Central",
  CanadaEastern = "Canada/Eastern",
  CanadaMountain = "Canada/Mountain",
  CanadaNewfoundland = "Canada/Newfoundland",
  CanadaPacific = "Canada/Pacific",
  CanadaSaskatchewan = "Canada/Saskatchewan",
  CanadaYukon = "Canada/Yukon",
  ChileContinental = "Chile/Continental",
  ChileEasterIsland = "Chile/EasterIsland",
  Cuba = "Cuba",
  EET = "EET",
  EST = "EST",
  EST5EDT = "EST5EDT",
  Egypt = "Egypt",
  Eire = "Eire",
  EtcGMT = "Etc/GMT",
  EtcGMTPlus0 = "Etc/GMT+0",
  EtcGMTPlus1 = "Etc/GMT+1",
  EtcGMTPlus10 = "Etc/GMT+10",
  EtcGMTPlus11 = "Etc/GMT+11",
  EtcGMTPlus12 = "Etc/GMT+12",
  EtcGMTPlus2 = "Etc/GMT+2",
  EtcGMTPlus3 = "Etc/GMT+3",
  EtcGMTPlus4 = "Etc/GMT+4",
  EtcGMTPlus5 = "Etc/GMT+5",
  EtcGMTPlus6 = "Etc/GMT+6",
  EtcGMTPlus7 = "Etc/GMT+7",
  EtcGMTPlus8 = "Etc/GMT+8",
  EtcGMTPlus9 = "Etc/GMT+9",
  EtcGMTMinus0 = "Etc/GMT-0",
  EtcGMTMinus1 = "Etc/GMT-1",
  EtcGMTMinus10 = "Etc/GMT-10",
  EtcGMTMinus11 = "Etc/GMT-11",
  EtcGMTMinus12 = "Etc/GMT-12",
  EtcGMTMinus13 = "Etc/GMT-13",
  EtcGMTMinus14 = "Etc/GMT-14",
  EtcGMTMinus2 = "Etc/GMT-2",
  EtcGMTMinus3 = "Etc/GMT-3",
  EtcGMTMinus4 = "Etc/GMT-4",
  EtcGMTMinus5 = "Etc/GMT-5",
  EtcGMTMinus6 = "Etc/GMT-6",
  EtcGMTMinus7 = "Etc/GMT-7",
  EtcGMTMinus8 = "Etc/GMT-8",
  EtcGMTMinus9 = "Etc/GMT-9",
  EtcGMT0 = "Etc/GMT0",
  EtcGreenwich = "Etc/Greenwich",
  EtcUCT = "Etc/UCT",
  EtcUTC = "Etc/UTC",
  EtcUniversal = "Etc/Universal",
  EtcZulu = "Etc/Zulu",
  EuropeAmsterdam = "Europe/Amsterdam",
  EuropeAndorra = "Europe/Andorra",
  EuropeAstrakhan = "Europe/Astrakhan",
  EuropeAthens = "Europe/Athens",
  EuropeBelfast = "Europe/Belfast",
  EuropeBelgrade = "Europe/Belgrade",
  EuropeBerlin = "Europe/Berlin",
  EuropeBratislava = "Europe/Bratislava",
  EuropeBrussels = "Europe/Brussels",
  EuropeBucharest = "Europe/Bucharest",
  EuropeBudapest = "Europe/Budapest",
  EuropeBusingen = "Europe/Busingen",
  EuropeChisinau = "Europe/Chisinau",
  EuropeCopenhagen = "Europe/Copenhagen",
  EuropeDublin = "Europe/Dublin",
  EuropeGibraltar = "Europe/Gibraltar",
  EuropeGuernsey = "Europe/Guernsey",
  EuropeHelsinki = "Europe/Helsinki",
  EuropeIsleofMan = "Europe/Isle_of_Man",
  EuropeIstanbul = "Europe/Istanbul",
  EuropeJersey = "Europe/Jersey",
  EuropeKaliningrad = "Europe/Kaliningrad",
  EuropeKiev = "Europe/Kiev",
  EuropeKirov = "Europe/Kirov",
  EuropeLisbon = "Europe/Lisbon",
  EuropeLjubljana = "Europe/Ljubljana",
  EuropeLondon = "Europe/London",
  EuropeLuxembourg = "Europe/Luxembourg",
  EuropeMadrid = "Europe/Madrid",
  EuropeMalta = "Europe/Malta",
  EuropeMariehamn = "Europe/Mariehamn",
  EuropeMinsk = "Europe/Minsk",
  EuropeMonaco = "Europe/Monaco",
  EuropeMoscow = "Europe/Moscow",
  EuropeNicosia = "Europe/Nicosia",
  EuropeOslo = "Europe/Oslo",
  EuropeParis = "Europe/Paris",
  EuropePodgorica = "Europe/Podgorica",
  EuropePrague = "Europe/Prague",
  EuropeRiga = "Europe/Riga",
  EuropeRome = "Europe/Rome",
  EuropeSamara = "Europe/Samara",
  EuropeSanMarino = "Europe/San_Marino",
  EuropeSarajevo = "Europe/Sarajevo",
  EuropeSaratov = "Europe/Saratov",
  EuropeSimferopol = "Europe/Simferopol",
  EuropeSkopje = "Europe/Skopje",
  EuropeSofia = "Europe/Sofia",
  EuropeStockholm = "Europe/Stockholm",
  EuropeTallinn = "Europe/Tallinn",
  EuropeTirane = "Europe/Tirane",
  EuropeTiraspol = "Europe/Tiraspol",
  EuropeUlyanovsk = "Europe/Ulyanovsk",
  EuropeUzhgorod = "Europe/Uzhgorod",
  EuropeVaduz = "Europe/Vaduz",
  EuropeVatican = "Europe/Vatican",
  EuropeVienna = "Europe/Vienna",
  EuropeVilnius = "Europe/Vilnius",
  EuropeVolgograd = "Europe/Volgograd",
  EuropeWarsaw = "Europe/Warsaw",
  EuropeZagreb = "Europe/Zagreb",
  EuropeZaporozhye = "Europe/Zaporozhye",
  EuropeZurich = "Europe/Zurich",
  GB = "GB",
  GBEire = "GB-Eire",
  GMT = "GMT",
  GMTPlus0 = "GMT+0",
  GMTMinus0 = "GMT-0",
  GMT0 = "GMT0",
  Greenwich = "Greenwich",
  HST = "HST",
  Hongkong = "Hongkong",
  Iceland = "Iceland",
  IndianAntananarivo = "Indian/Antananarivo",
  IndianChagos = "Indian/Chagos",
  IndianChristmas = "Indian/Christmas",
  IndianCocos = "Indian/Cocos",
  IndianComoro = "Indian/Comoro",
  IndianKerguelen = "Indian/Kerguelen",
  IndianMahe = "Indian/Mahe",
  IndianMaldives = "Indian/Maldives",
  IndianMauritius = "Indian/Mauritius",
  IndianMayotte = "Indian/Mayotte",
  IndianReunion = "Indian/Reunion",
  Iran = "Iran",
  Israel = "Israel",
  Jamaica = "Jamaica",
  Japan = "Japan",
  Kwajalein = "Kwajalein",
  Libya = "Libya",
  MET = "MET",
  MST = "MST",
  MST7MDT = "MST7MDT",
  MexicoBajaNorte = "Mexico/BajaNorte",
  MexicoBajaSur = "Mexico/BajaSur",
  MexicoGeneral = "Mexico/General",
  NZ = "NZ",
  NZCHAT = "NZ-CHAT",
  Navajo = "Navajo",
  PRC = "PRC",
  PST8PDT = "PST8PDT",
  PacificApia = "Pacific/Apia",
  PacificAuckland = "Pacific/Auckland",
  PacificBougainville = "Pacific/Bougainville",
  PacificChatham = "Pacific/Chatham",
  PacificChuuk = "Pacific/Chuuk",
  PacificEaster = "Pacific/Easter",
  PacificEfate = "Pacific/Efate",
  PacificEnderbury = "Pacific/Enderbury",
  PacificFakaofo = "Pacific/Fakaofo",
  PacificFiji = "Pacific/Fiji",
  PacificFunafuti = "Pacific/Funafuti",
  PacificGalapagos = "Pacific/Galapagos",
  PacificGambier = "Pacific/Gambier",
  PacificGuadalcanal = "Pacific/Guadalcanal",
  PacificGuam = "Pacific/Guam",
  PacificHonolulu = "Pacific/Honolulu",
  PacificJohnston = "Pacific/Johnston",
  PacificKiritimati = "Pacific/Kiritimati",
  PacificKosrae = "Pacific/Kosrae",
  PacificKwajalein = "Pacific/Kwajalein",
  PacificMajuro = "Pacific/Majuro",
  PacificMarquesas = "Pacific/Marquesas",
  PacificMidway = "Pacific/Midway",
  PacificNauru = "Pacific/Nauru",
  PacificNiue = "Pacific/Niue",
  PacificNorfolk = "Pacific/Norfolk",
  PacificNoumea = "Pacific/Noumea",
  PacificPagoPago = "Pacific/Pago_Pago",
  PacificPalau = "Pacific/Palau",
  PacificPitcairn = "Pacific/Pitcairn",
  PacificPohnpei = "Pacific/Pohnpei",
  PacificPonape = "Pacific/Ponape",
  PacificPortMoresby = "Pacific/Port_Moresby",
  PacificRarotonga = "Pacific/Rarotonga",
  PacificSaipan = "Pacific/Saipan",
  PacificSamoa = "Pacific/Samoa",
  PacificTahiti = "Pacific/Tahiti",
  PacificTarawa = "Pacific/Tarawa",
  PacificTongatapu = "Pacific/Tongatapu",
  PacificTruk = "Pacific/Truk",
  PacificWake = "Pacific/Wake",
  PacificWallis = "Pacific/Wallis",
  PacificYap = "Pacific/Yap",
  Poland = "Poland",
  Portugal = "Portugal",
  ROC = "ROC",
  ROK = "ROK",
  Singapore = "Singapore",
  Turkey = "Turkey",
  UCT = "UCT",
  USAlaska = "US/Alaska",
  USAleutian = "US/Aleutian",
  USArizona = "US/Arizona",
  USCentral = "US/Central",
  USEastIndiana = "US/East-Indiana",
  USEastern = "US/Eastern",
  USHawaii = "US/Hawaii",
  USIndianaStarke = "US/Indiana-Starke",
  USMichigan = "US/Michigan",
  USMountain = "US/Mountain",
  USPacific = "US/Pacific",
  USPacificNew = "US/Pacific-New",
  USSamoa = "US/Samoa",
  UTC = "UTC",
  Universal = "Universal",
  WSU = "W-SU",
  WET = "WET",
  Zulu = "Zulu",
}
